In [2]:
import requests
import pandas as pd
import time
import urllib.parse

c:\Users\ruedi.luethi\.conda\envs\streamlit\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [3]:
GENERATION_TO_REGION = {
    "generation-i": "Kanto",
    "generation-ii": "Johto",
    "generation-iii": "Hoenn",
    "generation-iv": "Sinnoh",
    "generation-v": "Unova",
    "generation-vi": "Kalos",
    "generation-vii": "Alola",
    "generation-viii": "Galar",
    "generation-ix": "Paldea",
}

TYPE_DE = {
    "normal": "Normal", "fire": "Feuer", "water": "Wasser", "electric": "Elektro",
    "grass": "Pflanze", "ice": "Eis", "fighting": "Kampf", "poison": "Gift",
    "ground": "Boden", "flying": "Flug", "psychic": "Psycho", "bug": "Käfer",
    "rock": "Gestein", "ghost": "Geist", "dragon": "Drache", "dark": "Unlicht",
    "steel": "Stahl", "fairy": "Fee",
}

In [5]:

def get_json(url, retries=3):
    for i in range(retries):
        try:
            r = requests.get(url, timeout=10)
            r.raise_for_status()
            return r.json()
        except Exception as e:
            if i == retries - 1:
                print(f"  Fehler bei {url}: {e}")
                return None
            time.sleep(1)

BULBA_API = "https://bulbapedia.bulbagarden.net/w/api.php"

def get_bulbapedia_sprite_urls(entries):
    """
    entries: list of (pokemon_id, name_en)
    Gibt dict {pokemon_id: url} zurück.
    Bulbapedia Dateiname: z.B. "0004Charmander.png"
    MediaWiki API erlaubt bis zu 50 Titles pro Request.
    """
    result = {}
    # Aufbauen: {filename: pokemon_id}
    filenames = {}
    for pid, name_en in entries:
        # Ersten Buchstaben gross, rest klein — Bulbapedia-Konvention
        name_cap = name_en.capitalize()
        filename = f"File:{pid:04d}{name_cap}.png"
        filenames[filename] = pid

    # In Batches von 50
    keys = list(filenames.keys())
    for i in range(0, len(keys), 50):
        batch = keys[i:i+50]
        titles = "|".join(batch)
        params = {
            "action": "query",
            "titles": titles,
            "prop": "imageinfo",
            "iiprop": "url",
            "format": "json",
        }
        try:
            r = requests.get(BULBA_API, params=params, timeout=15)
            data = r.json()
            pages = data.get("query", {}).get("pages", {})
            for page in pages.values():
                title = page.get("title", "")
                imageinfo = page.get("imageinfo", [])
                if imageinfo:
                    url = imageinfo[0].get("url", "")
                    pid = filenames.get(title)
                    if pid and url:
                        result[pid] = url
        except Exception as e:
            print(f"  Bulbapedia Fehler bei Batch {i}: {e}")
        time.sleep(0.2)

    return result

def get_de_name(names):
    for n in names:
        if n["language"]["name"] == "de":
            return n["name"]
    return None

def parse_evolution_chain(chain, result=None, stage=0):
    """Gibt Liste von (name, stage) zurück"""
    if result is None:
        result = []
    result.append((chain["species"]["name"], stage))
    for evo in chain.get("evolves_to", []):
        parse_evolution_chain(evo, result, stage + 1)
    return result

In [9]:
# Cache für Evolution Chains
evo_cache = {}

def get_evolution_chain(url):
    if url in evo_cache:
        return evo_cache[url]
    data = get_json(url)
    if not data:
        return []
    chain = parse_evolution_chain(data["chain"])
    evo_cache[url] = chain
    return chain

# Wie viele Pokémon holen? (1025 = alle, weniger zum Testen)
TOTAL = 1025

records = []

print(f"Hole {TOTAL} Pokémon von der PokeAPI...")

for pokemon_id in range(1, TOTAL + 1):
    if pokemon_id % 50 == 0:
        print(f"  {pokemon_id}/{TOTAL}...")

    # Call 1: Species → DE-Name, Generation, Region, Evo-Chain-URL
    species = get_json(f"https://pokeapi.co/api/v2/pokemon-species/{pokemon_id}/")
    if not species:
        continue

    name_de = get_de_name(species.get("names", []))
    name_en = next((n["name"] for n in species["names"] if n["language"]["name"] == "en"), None)
    generation = species.get("generation", {}).get("name", "")
    region = GENERATION_TO_REGION.get(generation, "")
    evo_chain_url = species.get("evolution_chain", {}).get("url", "")
    evolves_from = species.get("evolves_from_species", {})
    evolves_from_en = evolves_from["name"] if evolves_from else None

    # Entwicklungsstufe bestimmen
    evo_chain = get_evolution_chain(evo_chain_url) if evo_chain_url else []
    evo_stage = 0
    evo_names_en = [e[0] for e in evo_chain]
    for (evo_name, stage) in evo_chain:
        if evo_name == species["name"]:
            evo_stage = stage
            break

    # Call 2: Pokemon → Typen, Stats, Sprite
    pokemon = get_json(f"https://pokeapi.co/api/v2/pokemon/{pokemon_id}/")
    if not pokemon:
        continue

    types = [t["type"]["name"] for t in pokemon.get("types", [])]
    type1_de = TYPE_DE.get(types[0], types[0]) if len(types) > 0 else ""
    type2_de = TYPE_DE.get(types[1], types[1]) if len(types) > 1 else ""

    stats = {s["stat"]["name"]: s["base_stat"] for s in pokemon.get("stats", [])}

    sprite_url = (
        pokemon.get("sprites", {})
        .get("other", {})
        .get("official-artwork", {})
        .get("front_default", "")
    )

    records.append({
        "nr": pokemon_id,
        "name_de": name_de,
        "name_en": name_en,
        "typ1": type1_de,
        "typ2": type2_de,
        "generation": generation.replace("generation-", "").upper(),
        "region": region,
        "entwicklungsstufe": evo_stage,
        "entwickelt_aus_en": evolves_from_en,
        "hp": stats.get("hp", ""),
        "angriff": stats.get("attack", ""),
        "verteidigung": stats.get("defense", ""),
        "spezial_angriff": stats.get("special-attack", ""),
        "spezial_verteidigung": stats.get("special-defense", ""),
        "initiative": stats.get("speed", ""),
        "sprite_url": sprite_url,
    })

    time.sleep(0.05)  # Rate limiting

df = pd.DataFrame(records)

# Deutschen Namen von evolves_from dazujointen
name_map = df.set_index("name_en")["name_de"].to_dict()
df["entwickelt_aus_de"] = df["entwickelt_aus_en"].map(name_map)

# Bulbapedia Sprites holen (in Batches)
print("\nHole Bulbapedia Sprites...")
entries = list(zip(df["nr"], df["name_en"]))
bulba_urls = get_bulbapedia_sprite_urls(entries)
df["sprite_bulbapedia"] = df["nr"].map(bulba_urls)
found = df["sprite_bulbapedia"].notna().sum()
print(f"  {found}/{len(df)} Bulbapedia Sprites gefunden")

# Spalten ordnen
cols = [
    "nr", "name_de", "name_en", "typ1", "typ2",
    "region", "generation", "entwicklungsstufe",
    "entwickelt_aus_de", "entwickelt_aus_en",
    "hp", "angriff", "verteidigung",
    "spezial_angriff", "spezial_verteidigung", "initiative",
    "sprite_url", "sprite_bulbapedia"
]
df = df[cols]

output_path = "../data/pokemon/pokedex.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"\nFertig! {len(df)} Pokémon gespeichert → {output_path}")
print(df.head(10).to_string())

Hole 1025 Pokémon von der PokeAPI...
  50/1025...
  100/1025...
  150/1025...
  200/1025...
  250/1025...
  300/1025...
  350/1025...
  400/1025...
  450/1025...
  500/1025...
  550/1025...
  600/1025...
  650/1025...
  700/1025...
  750/1025...
  800/1025...
  850/1025...
  900/1025...
  950/1025...
  1000/1025...

Hole Bulbapedia Sprites...
  989/1025 Bulbapedia Sprites gefunden

Fertig! 1025 Pokémon gespeichert → ../data/pokemon/pokedex.csv
   nr    name_de     name_en     typ1  typ2 region generation  entwicklungsstufe entwickelt_aus_de entwickelt_aus_en  hp  angriff  verteidigung  spezial_angriff  spezial_verteidigung  initiative                                                                                              sprite_url                                                      sprite_bulbapedia
0   1    Bisasam   Bulbasaur  Pflanze  Gift  Kanto          I                  0               NaN              None  45       49            49               65                    65          45   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png   https://archives.bulbagarden.net/media/upload/f/fb/0001Bulbasaur.png
1   2  Bisaknosp     Ivysaur  Pflanze  Gift  Kanto          I                  1               NaN         bulbasaur  60       62            63               80                    80          60   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png     https://archives.bulbagarden.net/media/upload/8/81/0002Ivysaur.png
2   3   Bisaflor    Venusaur  Pflanze  Gift  Kanto          I                  2               NaN           ivysaur  80       82            83              100                   100          80   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png    https://archives.bulbagarden.net/media/upload/6/6b/0003Venusaur.png
3   4   Glumanda  Charmander    Feuer        Kanto          I                  0               NaN              None  39       52            43               60                    50          65   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png  https://archives.bulbagarden.net/media/upload/2/27/0004Charmander.png
4   5    Glutexo  Charmeleon    Feuer        Kanto          I                  1               NaN        charmander  58       64            58               80                    65          80   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png  https://archives.bulbagarden.net/media/upload/0/05/0005Charmeleon.png
5   6     Glurak   Charizard    Feuer  Flug  Kanto          I                  2               NaN        charmeleon  78       84            78              109                    85         100   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png   https://archives.bulbagarden.net/media/upload/3/38/0006Charizard.png
6   7    Schiggy    Squirtle   Wasser        Kanto          I                  0               NaN              None  44       48            65               50                    64          43   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png    https://archives.bulbagarden.net/media/upload/5/54/0007Squirtle.png
7   8   Schillok   Wartortle   Wasser        Kanto          I                  1               NaN          squirtle  59       63            80               65                    80          58   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png   https://archives.bulbagarden.net/media/upload/0/0f/0008Wartortle.png
8   9     Turtok   Blastoise   Wasser        Kanto          I                  2               NaN         wartortle  79       83           100               85                   105          78   https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png   https://archives.bulbagarden.net/media/upload/0/0a/0009Blastoise.png
9  10      Raupy    Caterpie    Käfer        Kanto          I                  0               NaN              None  45       30            35               20                    20          45  https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png    https://archives.bulbagarden.net/media/upload/5/5e/0010Caterpie.png

In [21]:
from pathlib import Path
from urllib.parse import urlparse
import pandas as pd
import requests

# Input/Output paths
csv_path = Path("../data/pokemon/pokedex.csv")
out_dir = Path("../data/pokemon/sprites")
out_dir.mkdir(parents=True, exist_ok=True)

# Load Pokedex CSV
if not csv_path.exists():
    raise FileNotFoundError(f"CSV not found: {csv_path.resolve()}")

df = pd.read_csv(csv_path, encoding="utf-8-sig")
if "sprite_bulbapedia" not in df.columns:
    raise KeyError("Column 'sprite_bulbapedia' not found in pokedex.csv")

session = requests.Session()
session.headers.update({"User-Agent": "Mozilla/5.0 (compatible; sprite-downloader/1.0)"})

downloaded = 0
skipped = 0
failed = 0

for _, row in df.iterrows():
    url = row.get("sprite_bulbapedia")
    if pd.isna(url) or not str(url).strip():
        skipped += 1
        continue

    url = str(url).strip()

    # Build a deterministic filename: 4-digit pokedex number + original extension
    pokemon_id = int(row["nr"]) if "nr" in row and not pd.isna(row["nr"]) else None
    parsed = urlparse(url)
    ext = Path(parsed.path).suffix.lower() or ".png"

    if pokemon_id is not None:
        filename = f"{pokemon_id:04d}{ext}"
    else:
        fallback_name = Path(parsed.path).name or f"sprite_{downloaded + failed + skipped:04d}{ext}"
        filename = fallback_name

    target = out_dir / filename

    # Skip already downloaded files
    if target.exists() and target.stat().st_size > 0:
        skipped += 1
        continue

    print(f"Downloading {url} → {target.name}...")

    try:
        resp = session.get(url, timeout=20)
        resp.raise_for_status()

        content_type = resp.headers.get("Content-Type", "")
        if not content_type.startswith("image/"):
            raise ValueError(f"URL did not return an image: {content_type}")

        target.write_bytes(resp.content)
        downloaded += 1
    except Exception as e:
        failed += 1
        print(f"Fehler bei {url}: {e}")

print(f"Fertig. Downloaded={downloaded}, Skipped={skipped}, Failed={failed}")
print(f"Sprites gespeichert in: {out_dir.resolve()}")

Downloading https://archives.bulbagarden.net/media/upload/f/fb/0001Bulbasaur.png → 0001.png...
Downloading https://archives.bulbagarden.net/media/upload/8/81/0002Ivysaur.png → 0002.png...
Downloading https://archives.bulbagarden.net/media/upload/6/6b/0003Venusaur.png → 0003.png...
Downloading https://archives.bulbagarden.net/media/upload/2/27/0004Charmander.png → 0004.png...
Downloading https://archives.bulbagarden.net/media/upload/0/05/0005Charmeleon.png → 0005.png...
Downloading https://archives.bulbagarden.net/media/upload/3/38/0006Charizard.png → 0006.png...
Downloading https://archives.bulbagarden.net/media/upload/5/54/0007Squirtle.png → 0007.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0f/0008Wartortle.png → 0008.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0a/0009Blastoise.png → 0009.png...
Downloading https://archives.bulbagarden.net/media/upload/5/5e/0010Caterpie.png → 0010.png...
Downloading https://archives.bulbagarden.net/media/upload/d/da/0011Metapod.png → 0011.png...
Downloading https://archives.bulbagarden.net/media/upload/5/55/0012Butterfree.png → 0012.png...
Downloading https://archives.bulbagarden.net/media/upload/3/36/0013Weedle.png → 0013.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f3/0014Kakuna.png → 0014.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f7/0015Beedrill.png → 0015.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0c/0016Pidgey.png → 0016.png...
Downloading https://archives.bulbagarden.net/media/upload/8/82/0017Pidgeotto.png → 0017.png...
Downloading https://archives.bulbagarden.net/media/upload/7/73/0018Pidgeot.png → 0018.png...
Downloading https://archives.bulbagarden.net/media/upload/a/aa/0019Rattata.png → 0019.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2c/0020Raticate.png → 0020.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2d/0021Spearow.png → 0021.png...
Downloading https://archives.bulbagarden.net/media/upload/9/92/0022Fearow.png → 0022.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d2/0023Ekans.png → 0023.png...
Downloading https://archives.bulbagarden.net/media/upload/5/51/0024Arbok.png → 0024.png...
Downloading https://archives.bulbagarden.net/media/upload/4/4a/0025Pikachu.png → 0025.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b0/0026Raichu.png → 0026.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e9/0027Sandshrew.png → 0027.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a4/0028Sandslash.png → 0028.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b2/0029Nidoran.png → 0029.png...
Downloading https://archives.bulbagarden.net/media/upload/e/ea/0030Nidorina.png → 0030.png...
Downloading https://archives.bulbagarden.net/media/upload/9/9d/0031Nidoqueen.png → 0031.png...
Downloading https://archives.bulbagarden.net/media/upload/8/8c/0032Nidoran.png → 0032.png...
Downloading https://archives.bulbagarden.net/media/upload/1/1e/0033Nidorino.png → 0033.png...
Downloading https://archives.bulbagarden.net/media/upload/2/21/0034Nidoking.png → 0034.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b7/0035Clefairy.png → 0035.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a4/0036Clefable.png → 0036.png...
Downloading https://archives.bulbagarden.net/media/upload/0/06/0037Vulpix.png → 0037.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3e/0038Ninetales.png → 0038.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3a/0039Jigglypuff.png → 0039.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e2/0040Wigglytuff.png → 0040.png...
Downloading https://archives.bulbagarden.net/media/upload/4/4c/0041Zubat.png → 0041.png...
Downloading https://archives.bulbagarden.net/media/upload/7/76/0042Golbat.png → 0042.png...
Downloading https://archives.bulbagarden.net/media/upload/1/16/0043Oddish.png → 0043.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e0/0044Gloom.png → 0044.png...
Downloading https://archives.bulbagarden.net/media/upload/8/89/0045Vileplume.png → 0045.png...
Downloading https://archives.bulbagarden.net/media/upload/8/8a/0046Paras.png → 0046.png...
Downloading https://archives.bulbagarden.net/media/upload/7/7b/0047Parasect.png → 0047.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2c/0048Venonat.png → 0048.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0e/0049Venomoth.png → 0049.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a6/0050Diglett.png → 0050.png...
Downloading https://archives.bulbagarden.net/media/upload/8/88/0051Dugtrio.png → 0051.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d6/0052Meowth.png → 0052.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b0/0053Persian.png → 0053.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3f/0054Psyduck.png → 0054.png...
Downloading https://archives.bulbagarden.net/media/upload/e/ed/0055Golduck.png → 0055.png...
Downloading https://archives.bulbagarden.net/media/upload/f/fa/0056Mankey.png → 0056.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2c/0057Primeape.png → 0057.png...
Downloading https://archives.bulbagarden.net/media/upload/6/6a/0058Growlithe.png → 0058.png...
Downloading https://archives.bulbagarden.net/media/upload/4/42/0059Arcanine.png → 0059.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e4/0060Poliwag.png → 0060.png...
Downloading https://archives.bulbagarden.net/media/upload/f/fd/0061Poliwhirl.png → 0061.png...
Downloading https://archives.bulbagarden.net/media/upload/8/80/0062Poliwrath.png → 0062.png...
Downloading https://archives.bulbagarden.net/media/upload/b/bd/0063Abra.png → 0063.png...
Downloading https://archives.bulbagarden.net/media/upload/a/af/0064Kadabra.png → 0064.png...
Downloading https://archives.bulbagarden.net/media/upload/b/bb/0065Alakazam.png → 0065.png...
Downloading https://archives.bulbagarden.net/media/upload/0/02/0066Machop.png → 0066.png...
Downloading https://archives.bulbagarden.net/media/upload/2/22/0067Machoke.png → 0067.png...
Downloading https://archives.bulbagarden.net/media/upload/8/82/0068Machamp.png → 0068.png...
Downloading https://archives.bulbagarden.net/media/upload/6/66/0069Bellsprout.png → 0069.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c1/0070Weepinbell.png → 0070.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e9/0071Victreebel.png → 0071.png...
Downloading https://archives.bulbagarden.net/media/upload/6/6e/0072Tentacool.png → 0072.png...
Downloading https://archives.bulbagarden.net/media/upload/c/cb/0073Tentacruel.png → 0073.png...
Downloading https://archives.bulbagarden.net/media/upload/9/97/0074Geodude.png → 0074.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d4/0075Graveler.png → 0075.png...
Downloading https://archives.bulbagarden.net/media/upload/3/38/0076Golem.png → 0076.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c0/0077Ponyta.png → 0077.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a9/0078Rapidash.png → 0078.png...
Downloading https://archives.bulbagarden.net/media/upload/1/19/0079Slowpoke.png → 0079.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a3/0080Slowbro.png → 0080.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a2/0081Magnemite.png → 0081.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d9/0082Magneton.png → 0082.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b9/0084Doduo.png → 0084.png...
Downloading https://archives.bulbagarden.net/media/upload/9/97/0085Dodrio.png → 0085.png...
Downloading https://archives.bulbagarden.net/media/upload/2/22/0086Seel.png → 0086.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2b/0087Dewgong.png → 0087.png...
Downloading https://archives.bulbagarden.net/media/upload/e/eb/0088Grimer.png → 0088.png...
Downloading https://archives.bulbagarden.net/media/upload/4/41/0089Muk.png → 0089.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3e/0090Shellder.png → 0090.png...
Downloading https://archives.bulbagarden.net/media/upload/9/90/0091Cloyster.png → 0091.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c2/0092Gastly.png → 0092.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d1/0093Haunter.png → 0093.png...
Downloading https://archives.bulbagarden.net/media/upload/4/47/0094Gengar.png → 0094.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b7/0095Onix.png → 0095.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e4/0096Drowzee.png → 0096.png...
Downloading https://archives.bulbagarden.net/media/upload/4/4c/0097Hypno.png → 0097.png...
Downloading https://archives.bulbagarden.net/media/upload/e/ed/0098Krabby.png → 0098.png...
Downloading https://archives.bulbagarden.net/media/upload/a/ae/0099Kingler.png → 0099.png...
Downloading https://archives.bulbagarden.net/media/upload/5/55/0100Voltorb.png → 0100.png...
Downloading https://archives.bulbagarden.net/media/upload/d/db/0101Electrode.png → 0101.png...
Downloading https://archives.bulbagarden.net/media/upload/6/60/0102Exeggcute.png → 0102.png...
Downloading https://archives.bulbagarden.net/media/upload/a/ae/0103Exeggutor.png → 0103.png...
Downloading https://archives.bulbagarden.net/media/upload/1/19/0104Cubone.png → 0104.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a1/0105Marowak.png → 0105.png...
Downloading https://archives.bulbagarden.net/media/upload/0/00/0106Hitmonlee.png → 0106.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c0/0107Hitmonchan.png → 0107.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f2/0108Lickitung.png → 0108.png...
Downloading https://archives.bulbagarden.net/media/upload/1/16/0109Koffing.png → 0109.png...
Downloading https://archives.bulbagarden.net/media/upload/7/72/0110Weezing.png → 0110.png...
Downloading https://archives.bulbagarden.net/media/upload/7/7f/0111Rhyhorn.png → 0111.png...
Downloading https://archives.bulbagarden.net/media/upload/7/79/0112Rhydon.png → 0112.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c0/0113Chansey.png → 0113.png...
Downloading https://archives.bulbagarden.net/media/upload/2/22/0114Tangela.png → 0114.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e5/0115Kangaskhan.png → 0115.png...
Downloading https://archives.bulbagarden.net/media/upload/1/14/0116Horsea.png → 0116.png...
Downloading https://archives.bulbagarden.net/media/upload/2/22/0117Seadra.png → 0117.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b6/0118Goldeen.png → 0118.png...
Downloading https://archives.bulbagarden.net/media/upload/7/76/0119Seaking.png → 0119.png...
Downloading https://archives.bulbagarden.net/media/upload/3/38/0120Staryu.png → 0120.png...
Downloading https://archives.bulbagarden.net/media/upload/a/aa/0121Starmie.png → 0121.png...
Downloading https://archives.bulbagarden.net/media/upload/8/81/0123Scyther.png → 0123.png...
Downloading https://archives.bulbagarden.net/media/upload/0/07/0124Jynx.png → 0124.png...
Downloading https://archives.bulbagarden.net/media/upload/5/5c/0125Electabuzz.png → 0125.png...
Downloading https://archives.bulbagarden.net/media/upload/7/72/0126Magmar.png → 0126.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a9/0127Pinsir.png → 0127.png...
Downloading https://archives.bulbagarden.net/media/upload/a/ad/0128Tauros.png → 0128.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d1/0129Magikarp.png → 0129.png...
Downloading https://archives.bulbagarden.net/media/upload/b/bc/0130Gyarados.png → 0130.png...
Downloading https://archives.bulbagarden.net/media/upload/9/99/0131Lapras.png → 0131.png...
Downloading https://archives.bulbagarden.net/media/upload/2/25/0132Ditto.png → 0132.png...
Downloading https://archives.bulbagarden.net/media/upload/4/4c/0133Eevee.png → 0133.png...
Downloading https://archives.bulbagarden.net/media/upload/6/6d/0134Vaporeon.png → 0134.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e3/0135Jolteon.png → 0135.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f1/0136Flareon.png → 0136.png...
Downloading https://archives.bulbagarden.net/media/upload/8/8e/0137Porygon.png → 0137.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e6/0138Omanyte.png → 0138.png...
Downloading https://archives.bulbagarden.net/media/upload/6/66/0139Omastar.png → 0139.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d2/0140Kabuto.png → 0140.png...
Downloading https://archives.bulbagarden.net/media/upload/4/41/0141Kabutops.png → 0141.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2c/0142Aerodactyl.png → 0142.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3f/0143Snorlax.png → 0143.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d0/0144Articuno.png → 0144.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c6/0145Zapdos.png → 0145.png...
Downloading https://archives.bulbagarden.net/media/upload/2/21/0146Moltres.png → 0146.png...
Downloading https://archives.bulbagarden.net/media/upload/a/ae/0147Dratini.png → 0147.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0d/0148Dragonair.png → 0148.png...
Downloading https://archives.bulbagarden.net/media/upload/1/1c/0149Dragonite.png → 0149.png...
Downloading https://archives.bulbagarden.net/media/upload/8/89/0150Mewtwo.png → 0150.png...
Downloading https://archives.bulbagarden.net/media/upload/9/9a/0151Mew.png → 0151.png...
Downloading https://archives.bulbagarden.net/media/upload/b/bc/0152Chikorita.png → 0152.png...
Downloading https://archives.bulbagarden.net/media/upload/8/85/0153Bayleef.png → 0153.png...
Downloading https://archives.bulbagarden.net/media/upload/8/8b/0154Meganium.png → 0154.png...
Downloading https://archives.bulbagarden.net/media/upload/9/97/0155Cyndaquil.png → 0155.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3f/0156Quilava.png → 0156.png...
Downloading https://archives.bulbagarden.net/media/upload/1/13/0157Typhlosion.png → 0157.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f7/0158Totodile.png → 0158.png...
Downloading https://archives.bulbagarden.net/media/upload/0/03/0159Croconaw.png → 0159.png...
Downloading https://archives.bulbagarden.net/media/upload/2/29/0160Feraligatr.png → 0160.png...
Downloading https://archives.bulbagarden.net/media/upload/3/34/0161Sentret.png → 0161.png...
Downloading https://archives.bulbagarden.net/media/upload/a/a8/0162Furret.png → 0162.png...
Downloading https://archives.bulbagarden.net/media/upload/3/38/0163Hoothoot.png → 0163.png...
Downloading https://archives.bulbagarden.net/media/upload/1/14/0164Noctowl.png → 0164.png...
Downloading https://archives.bulbagarden.net/media/upload/9/91/0165Ledyba.png → 0165.png...
Downloading https://archives.bulbagarden.net/media/upload/4/4f/0166Ledian.png → 0166.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2b/0167Spinarak.png → 0167.png...
Downloading https://archives.bulbagarden.net/media/upload/5/5c/0168Ariados.png → 0168.png...
Downloading https://archives.bulbagarden.net/media/upload/3/35/0169Crobat.png → 0169.png...
Downloading https://archives.bulbagarden.net/media/upload/c/ca/0170Chinchou.png → 0170.png...
Downloading https://archives.bulbagarden.net/media/upload/0/09/0171Lanturn.png → 0171.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f3/0172Pichu.png → 0172.png...
Downloading https://archives.bulbagarden.net/media/upload/7/73/0173Cleffa.png → 0173.png...
Downloading https://archives.bulbagarden.net/media/upload/0/06/0174Igglybuff.png → 0174.png...
Downloading https://archives.bulbagarden.net/media/upload/0/01/0175Togepi.png → 0175.png...
Downloading https://archives.bulbagarden.net/media/upload/3/3b/0176Togetic.png → 0176.png...
Downloading https://archives.bulbagarden.net/media/upload/7/71/0177Natu.png → 0177.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c3/0178Xatu.png → 0178.png...
Downloading https://archives.bulbagarden.net/media/upload/1/16/0179Mareep.png → 0179.png...
Downloading https://archives.bulbagarden.net/media/upload/1/19/0180Flaaffy.png → 0180.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c2/0181Ampharos.png → 0181.png...
Downloading https://archives.bulbagarden.net/media/upload/5/51/0182Bellossom.png → 0182.png...
Downloading https://archives.bulbagarden.net/media/upload/8/8e/0183Marill.png → 0183.png...
Downloading https://archives.bulbagarden.net/media/upload/2/22/0184Azumarill.png → 0184.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2f/0185Sudowoodo.png → 0185.png...
Downloading https://archives.bulbagarden.net/media/upload/9/9b/0186Politoed.png → 0186.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c9/0187Hoppip.png → 0187.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f2/0188Skiploom.png → 0188.png...
Downloading https://archives.bulbagarden.net/media/upload/6/64/0189Jumpluff.png → 0189.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0d/0190Aipom.png → 0190.png...
Downloading https://archives.bulbagarden.net/media/upload/6/67/0191Sunkern.png → 0191.png...
Downloading https://archives.bulbagarden.net/media/upload/0/0d/0192Sunflora.png → 0192.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2d/0193Yanma.png → 0193.png...
Downloading https://archives.bulbagarden.net/media/upload/f/f7/0194Wooper.png → 0194.png...
Downloading https://archives.bulbagarden.net/media/upload/0/01/0195Quagsire.png → 0195.png...
Downloading https://archives.bulbagarden.net/media/upload/6/67/0196Espeon.png → 0196.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e1/0197Umbreon.png → 0197.png...
Downloading https://archives.bulbagarden.net/media/upload/e/e7/0198Murkrow.png → 0198.png...
Downloading https://archives.bulbagarden.net/media/upload/8/89/0199Slowking.png → 0199.png...
Downloading https://archives.bulbagarden.net/media/upload/1/1f/0200Misdreavus.png → 0200.png...
Downloading https://archives.bulbagarden.net/media/upload/b/b4/0201Unown.png → 0201.png...
Downloading https://archives.bulbagarden.net/media/upload/7/7d/0202Wobbuffet.png → 0202.png...
Downloading https://archives.bulbagarden.net/media/upload/6/65/0203Girafarig.png → 0203.png...
Downloading https://archives.bulbagarden.net/media/upload/7/7a/0204Pineco.png → 0204.png...
Downloading https://archives.bulbagarden.net/media/upload/4/45/0205Forretress.png → 0205.png...
Downloading https://archives.bulbagarden.net/media/upload/c/c0/0206Dunsparce.png → 0206.png...
Downloading https://archives.bulbagarden.net/media/upload/4/49/0207Gligar.png → 0207.png...
Downloading https://archives.bulbagarden.net/media/upload/2/2a/0208Steelix.png → 0208.png...
Downloading https://archives.bulbagarden.net/media/upload/2/24/0209Snubbull.png → 0209.png...
Downloading https://archives.bulbagarden.net/media/upload/e/eb/0210Granbull.png → 0210.png...
Downloading https://archives.bulbagarden.net/media/upload/b/bb/0211Qwilfish.png → 0211.png...
Downloading https://archives.bulbagarden.net/media/upload/3/39/0212Scizor.png → 0212.png...
Downloading https://archives.bulbagarden.net/media/upload/5/59/0213Shuckle.png → 0213.png...
Downloading https://archives.bulbagarden.net/media/upload/7/75/0214Heracross.png → 0214.png...
Downloading https://archives.bulbagarden.net/media/upload/d/d4/0215Sneasel.png → 0215.png...
Downloading https://archives.bulbagarden.net/media/upload/1/11/0216Teddiursa.png → 0216.png...

In [2]:
from pathlib import Path
import pandas as pd

csv_path = Path("../data/pokemon/pokedex.csv")
out_dir = Path("../data/pokemon/sprites")
out_dir.mkdir(parents=True, exist_ok=True)

# Load Pokedex CSV
if not csv_path.exists():
    raise FileNotFoundError(f"CSV not found: {csv_path.resolve()}")

df = pd.read_csv(csv_path, encoding="utf-8-sig")

# --- Recursive evolution lookup from entwickelt_aus_en ---
# Normalize keys to avoid case/whitespace mismatches.
name_norm = df["name_en"].astype(str).str.strip().str.lower()
parent_norm = df["entwickelt_aus_en"].fillna("").astype(str).str.strip().str.lower()

df_lookup = pd.DataFrame({"name": name_norm, "parent": parent_norm})

# child -> parent mapping from CSV
parent_of = {
    row["name"]: row["parent"]
    for _, row in df_lookup.iterrows()
    if row["name"]
}

# Build parent -> [children] mapping
children_of = {}
for child, parent in parent_of.items():
    if not parent:
        continue
    children_of.setdefault(parent, []).append(child)

for parent in children_of:
    children_of[parent].sort()


def collect_leaf_paths(name, path=None):
    if path is None:
        path = []
    path = path + [name]
    children = children_of.get(name, [])
    if not children:
        return [path]

    paths = []
    for child in children:
        paths.extend(collect_leaf_paths(child, path))
    return paths


def full_evolution_sequence(name):
    if pd.isna(name) or not str(name).strip():
        return []

    name = str(name).strip().lower()

    # Move to root (first stage) by following parents upward
    root = name
    seen_up = set()
    while True:
        if root in seen_up:
            break
        seen_up.add(root)

        parent = parent_of.get(root, "")
        if not parent:
            break
        root = parent

    # Build all root->leaf paths recursively
    paths = collect_leaf_paths(root)

    # Keep only paths that include current pokemon
    relevant_paths = [p for p in paths if name in p]
    if not relevant_paths:
        return []

    # Only keep chains with at least 2 stages.
    if not any(len(p) > 1 for p in relevant_paths):
        return []

    # Return as list object in df (merged unique order for branch evolutions)
    merged = []
    for path in relevant_paths:
        for p in path:
            if p not in merged:
                merged.append(p)
    return merged


df["entwicklungsabfolge_en"] = df["name_en"].apply(full_evolution_sequence)

# Optional DE list version
de_name_of = dict(zip(df["name_en"].astype(str).str.strip().str.lower(), df["name_de"]))


def to_de_list(seq_en):
    return [de_name_of.get(n, n) for n in seq_en] if isinstance(seq_en, list) else []


df["entwicklungsabfolge_de"] = df["entwicklungsabfolge_en"].apply(to_de_list)

# Additional list with pokedex numbers for the evolution sequence
nr_of = dict(zip(df["name_en"].astype(str).str.strip().str.lower(), df["nr"]))


def to_nr_list(seq_en):
    if not isinstance(seq_en, list):
        return []
    return [int(nr_of[n]) for n in seq_en if n in nr_of and pd.notna(nr_of[n])]


df["entwicklungsabfolge_nr"] = df["entwicklungsabfolge_en"].apply(to_nr_list)

# Show first rows for quick validation
# print(df[["nr", "name_en", "entwickelt_aus_en", "entwicklungsabfolge_en", "entwicklungsabfolge_nr"]].head(10).to_string(index=False))
df.head()


# df['typ1'].value_counts()
# df['typ2'].value_counts()

,nr,name_de,name_en,typ1,typ2,region,generation,entwicklungsstufe,entwickelt_aus_de,entwickelt_aus_en,...,angriff,verteidigung,spezial_angriff,spezial_verteidigung,initiative,sprite_url,sprite_bulbapedia,entwicklungsabfolge_en,entwicklungsabfolge_de,entwicklungsabfolge_nr
0,1,Bisasam,Bulbasaur,Pflanze,Gift,Kanto,I,0,NaN,NaN,...,49,49,65,65,45,https://raw.githubusercontent.com/PokeAPI/spri...,https://archives.bulbagarden.net/media/upload/...,"[bulbasaur, ivysaur, venusaur]","[Bisasam, Bisaknosp, Bisaflor]","[1, 2, 3]"
1,2,Bisaknosp,Ivysaur,Pflanze,Gift,Kanto,I,1,NaN,bulbasaur,...,62,63,80,80,60,https://raw.githubusercontent.com/PokeAPI/spri...,https://archives.bulbagarden.net/media/upload/...,"[bulbasaur, ivysaur, venusaur]","[Bisasam, Bisaknosp, Bisaflor]","[1, 2, 3]"
2,3,Bisaflor,Venusaur,Pflanze,Gift,Kanto,I,2,NaN,ivysaur,...,82,83,100,100,80,https://raw.githubusercontent.com/PokeAPI/spri...,https://archives.bulbagarden.net/media/upload/...,"[bulbasaur, ivysaur, venusaur]","[Bisasam, Bisaknosp, Bisaflor]","[1, 2, 3]"
3,4,Glumanda,Charmander,Feuer,NaN,Kanto,I,0,NaN,NaN,...,52,43,60,50,65,https://raw.githubusercontent.com/PokeAPI/spri...,https://archives.bulbagarden.net/media/upload/...,"[charmander, charmeleon, charizard]","[Glumanda, Glutexo, Glurak]","[4, 5, 6]"
4,5,Glutexo,Charmeleon,Feuer,NaN,Kanto,I,1,NaN,charmander,...,64,58,80,65,80,https://raw.githubusercontent.com/PokeAPI/spri...,https://archives.bulbagarden.net/media/upload/...,"[charmander, charmeleon, charizard]","[Glumanda, Glutexo, Glurak]","[4, 5, 6]"

In [7]:
# Neues DataFrame mit den gewuenschten Spalten
df_new = df[[
    "nr",
    "name_de",
    "name_en",
    "typ1",
    "typ2",
    "region",
    "generation",
    "entwicklungsstufe",
    "entwickelt_aus_en",
    "sprite_url",
    "sprite_bulbapedia",
    "entwicklungsabfolge_nr",
]].copy()

# Fuer JSON-Export: zusaetzliche Verschachtelung [] um jede Liste
df_new_export = df_new.copy()
df_new_export["entwicklungsabfolge_nr"] = df_new_export["entwicklungsabfolge_nr"].apply(
    lambda seq: [seq] if isinstance(seq, list) else [[]]
)

json_path = "../data/pokemon/pokedex_new.json"
df_new_export.to_json(json_path, orient="records", force_ascii=False, indent=2)

In [20]:
# json_path = "../data/pokemon/pokedex_edited.json"
json_path = "../data/pokemon/pokedex_extended_cleaned.json"
df_edited = pd.read_json(json_path, orient="records")

out_dir = Path("../data/pokemon/sprites")
# df_edited.iloc[15:25].head()

for k_, pokemon in df_edited.iterrows():
    forms = pokemon.get("weitere_erscheinungsformen")
    # if pd.notna(pokemon["weitere_erscheinungsformen"]):
    if isinstance(forms, list) and len(forms) > 0:
        print(f"{pokemon['name_de']} hat weitere Erscheinungsformen:")
        pokemon_id = int(pokemon["nr"])

        for form in pokemon["weitere_erscheinungsformen"]:
            sprite_path = out_dir / f"{pokemon_id:04d}_{form['form_name']}.png"
            if not sprite_path.exists():
                r = requests.get(form["sprite_bulbapedia"], timeout=20)
                r.raise_for_status()
                sprite_path.write_bytes(r.content)
                print(f"geladen: {sprite_path}")
            else:
                print(f"existiert: {sprite_path}")

Bisaflor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0003_Mega.png
geladen: ..\data\pokemon\sprites\0003_Gigantamax.png
Glurak hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0006_Mega_X.png
geladen: ..\data\pokemon\sprites\0006_Mega_Y.png
geladen: ..\data\pokemon\sprites\0006_Gigantamax.png
Turtok hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0009_Mega.png
geladen: ..\data\pokemon\sprites\0009_Gigantamax.png
Smettbo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0012_Gigantamax.png
Bibor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0015_Mega.png
Tauboss hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0018_Mega.png
Rattfratz hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0019_Alola.png
Rattikarl hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0020_Alola.png
Pikachu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0025_Cosplay.png
geladen: ..\data\pokemon\sprites\0025_Partner_Cap.png
geladen: ..\data\pokemon\sprites\0025_Gigantamax.png
Raichu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0026_Alola.png
geladen: ..\data\pokemon\sprites\0026_Mega_X.png
geladen: ..\data\pokemon\sprites\0026_Mega_Y.png
Sandan hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0027_Alola.png
Sandamer hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0028_Alola.png
Pixi hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0036_Mega.png
Vulpix hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0037_Alola.png
Vulnona hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0038_Alola.png
Digda hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0050_Alola.png
Digdri hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0051_Alola.png
Mauzi hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0052_Alola.png
geladen: ..\data\pokemon\sprites\0052_Galar.png
geladen: ..\data\pokemon\sprites\0052_Gigantamax.png
Snobilikat hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0053_Alola.png
Fukano hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0058_Hisui.png
Arkani hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0059_Hisui.png
Simsala hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0065_Mega.png
Machomei hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0068_Gigantamax.png
Sarzenia hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0071_Mega.png
Kleinstein hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0074_Alola.png
Georok hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0075_Alola.png
Geowaz hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0076_Alola.png
Ponita hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0077_Galar.png
Gallopa hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0078_Galar.png
Flegmon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0079_Galar.png
Lahmus hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0080_Galar.png
geladen: ..\data\pokemon\sprites\0080_Mega.png
Porenta hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0083_Galar.png
Sleima hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0088_Alola.png
Sleimok hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0089_Alola.png
Gengar hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0094_Mega.png
geladen: ..\data\pokemon\sprites\0094_Gigantamax.png
Kingler hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0099_Gigantamax.png
Voltobal hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0100_Hisui.png
Lektrobal hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0101_Hisui.png
Kokowei hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0103_Alola.png
Knogga hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0105_Alola.png
Smogmog hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0110_Galar.png
Kangama hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0115_Mega.png
Starmie hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0121_Mega.png
Pantimos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0122_Mime-Galar.png
Pinsir hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0127_Mega.png
Tauros hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0128_Paldea_Combat.png
geladen: ..\data\pokemon\sprites\0128_Paldea_Blaze.png
geladen: ..\data\pokemon\sprites\0128_Paldea_Aqua.png
Garados hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0130_Mega.png
Lapras hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0131_Gigantamax.png
Evoli hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0133_Gigantamax.png
Aerodactyl hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0142_Mega.png
Relaxo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0143_Moos.png
geladen: ..\data\pokemon\sprites\0143_Gigantamax.png
Arktos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0144_Galar.png
Zapdos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0145_Galar.png
Lavados hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0146_Galar.png
Dragoran hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0149_Mega.png
Mewtu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0150_Mega_X.png
geladen: ..\data\pokemon\sprites\0150_Mega_Y.png
Meganie hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0154_Mega.png
Tornupto hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0157_Hisui.png
Impergator hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0160_Mega.png
Pichu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0172_spiky.png
Ampharos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0181_Mega.png
Felino hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0194_Paldea.png
Laschoking hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0199_Galar.png
Stahlos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0208_Mega.png
Baldorfish hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0211_Hisui.png
Scherox hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0212_Mega.png
Skaraborn hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0214_Mega.png
Sniebel hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0215_Hisui.png
Corasonn hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0222_Galar.png
Panzaeron hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0227_Mega.png
Hundemon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0229_Mega.png
Despotar hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0248_Mega.png
Gewaldro hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0254_Mega.png
Lohgock hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0257_Mega.png
Sumpex hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0260_Mega.png
Zigzachs hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0263_Galar.png
Geradaks hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0264_Galar.png
Guardevoir hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0282_Mega.png
Zobiris hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0302_Mega.png
Flunkifer hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0303_Mega.png
Stolloss hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0306_Mega.png
Meditalis hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0308_Mega.png
Voltenso hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0310_Mega.png
Tohaido hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0319_Mega.png
Camerupt hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0323_Mega.png
Altaria hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0334_Mega.png
Formeo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0351_Sunny.png
geladen: ..\data\pokemon\sprites\0351_Rainy.png
geladen: ..\data\pokemon\sprites\0351_Snowy.png
Banette hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0354_Mega.png
Palimpalim hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0358_Mega.png
Absol hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0359_Mega.png
geladen: ..\data\pokemon\sprites\0359_Mega_Z.png
Firnontor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0362_Mega.png
Brutalanda hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0373_Mega.png
Metagross hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0376_Mega.png
Latias hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0380_Mega.png
Latios hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0381_Mega.png
Kyogre hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0382_Primal.png
Groudon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0383_Primal.png
Rayquaza hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0384_Mega.png
Deoxys hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0386_Attack.png
geladen: ..\data\pokemon\sprites\0386_Defense.png
geladen: ..\data\pokemon\sprites\0386_Speed.png
Staraptor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0398_Mega.png
Burmy hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0412_Sandy.png
geladen: ..\data\pokemon\sprites\0412_Trash.png
Burmadame hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0413_Sandy.png
geladen: ..\data\pokemon\sprites\0413_Trash.png
Kinoso hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0421_Sunshine.png
Schalellos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0422_East.png
Gastrodon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0423_East.png
Schlapor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0428_Mega.png
Knakrack hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0445_Mega.png
geladen: ..\data\pokemon\sprites\0445_Mega_Z.png
Lucario hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0448_Mega.png
geladen: ..\data\pokemon\sprites\0448_Mega_Z.png
Rexblisar hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0460_Mega.png
Galagladi hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0475_Mega.png
Frosdedje hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0478_Mega.png
Rotom hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0479_Heat.png
geladen: ..\data\pokemon\sprites\0479_Wash.png
geladen: ..\data\pokemon\sprites\0479_Frost.png
geladen: ..\data\pokemon\sprites\0479_Fan.png
geladen: ..\data\pokemon\sprites\0479_Mow.png
Dialga hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0483_Origin.png
Palkia hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0484_Origin.png
Heatran hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0485_Mega.png
Giratina hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0487_Origin.png
Darkrai hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0491_Mega.png
Shaymin hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0492_Sky.png
Flambirex hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0500_Mega.png
Admurai hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0503_Hisui.png
Stalobor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0530_Mega.png
Ohrdoch hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0531_Mega.png
Cerapendra hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0545_Mega.png
Dressella hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0549_Hisui.png
Barschuft hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0550_Blue.png
geladen: ..\data\pokemon\sprites\0550_White.png
Flampion hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0554_Galar.png
Flampivian hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0555_Zen.png
geladen: ..\data\pokemon\sprites\0555_Galar.png
geladen: ..\data\pokemon\sprites\0555_Galar_Zen.png
Irokex hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0560_Mega.png
Makabaja hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0562_Galar.png
Deponitox hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0569_Gigantamax.png
Zorua hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0570_Hisui.png
Zoroark hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0571_Hisui.png
Sesokitz hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0585_Summer.png
geladen: ..\data\pokemon\sprites\0585_Autumn.png
geladen: ..\data\pokemon\sprites\0585_Winter.png
Kronjuwild hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0586_Summer.png
geladen: ..\data\pokemon\sprites\0586_Autumn.png
geladen: ..\data\pokemon\sprites\0586_Winter.png
Zapplarang hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0604_Mega.png
Skelabra hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0609_Mega.png
Flunschlik hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0618_Galar.png
Golgantes hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0623_Mega.png
Washakwil hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0628_Hisui.png
Boreos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0641_Therian.png
Voltolos hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0642_Therian.png
Demeteros hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0645_Therian.png
Kyurem hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0646_White.png
geladen: ..\data\pokemon\sprites\0646_Black.png
Keldeo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0647_Resolute.png
Meloetta hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0648_Pirouette.png
Brigaron hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0652_Mega.png
Fennexis hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0655_Mega.png
Quajutsu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0658_Ash.png
geladen: ..\data\pokemon\sprites\0658_Mega.png
Pyroleo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0668_Mega.png
Floette hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0670_Eternal.png
geladen: ..\data\pokemon\sprites\0670_Mega.png
Psiaugon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0678_Female.png
geladen: ..\data\pokemon\sprites\0678_Mega.png
Durengard hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0681_Blade.png
Calamanero hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0687_Mega.png
Thanathora hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0689_Mega.png
Tandrak hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0691_Mega.png
Resladero hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0701_Mega.png
Viscargot hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0705_Hisui.png
Viscogon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0706_Hisui.png
Arktilas hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0713_Hisui.png
Zygarde hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0718_10Percent.png
geladen: ..\data\pokemon\sprites\0718_Complete.png
geladen: ..\data\pokemon\sprites\0718_Mega.png
Diancie hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0719_Mega.png
Hoopa hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0720_Unbound.png
Silvarro hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0724_Hisui.png
Krawell hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0740_Mega.png
Choreogel hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0741_Pom-Pom.png
geladen: ..\data\pokemon\sprites\0741_Pa'u.png
geladen: ..\data\pokemon\sprites\0741_Sensu.png
Wolwerock hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0745_Midnight.png
geladen: ..\data\pokemon\sprites\0745_Dusk.png
Lusardin hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0746_School.png
Tectass hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0768_Mega.png
Meteno hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0774_Core.png
Sen-Long hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0780_Mega.png
Necrozma hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0800_Dusk_Mane.png
geladen: ..\data\pokemon\sprites\0800_Dawn_Wings.png
geladen: ..\data\pokemon\sprites\0800_Ultra.png
Magearna hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0801_Original.png
geladen: ..\data\pokemon\sprites\0801_Mega.png
geladen: ..\data\pokemon\sprites\0801_Original_Mega.png
Zeraora hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0807_Mega.png
Melmetal hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0809_Gigantamax.png
Gortrom hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0812_Gigantamax.png
Liberlo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0815_Gigantamax.png
Intelleon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0818_Gigantamax.png
Krarmor hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0823_Gigantamax.png
Maritellit hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0826_Gigantamax.png
Kamalm hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0834_Gigantamax.png
Montecarbo hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0839_Gigantamax.png
Drapfel hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0841_Gigantamax.png
Sanaconda hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0844_Gigantamax.png
Riffex hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0849_Low_Key.png
geladen: ..\data\pokemon\sprites\0849_Gigantamax.png
Infernopod hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0851_Gigantamax.png
Silembrim hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0858_Gigantamax.png
Olangaar hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0861_Gigantamax.png
Pokusan hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0869_Gigantamax.png
Legios hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0870_Mega.png
Kubuin hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0875_Noice.png
Servol hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0876_Female.png
Morpeko hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0877_Hangry.png
Patinaraja hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0879_Gigantamax.png
Duraludon hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0884_Gigantamax.png
Wulaosu hat weitere Erscheinungsformen:
geladen: ..\data\pokemon\sprites\0892_Rapid_Strike.png
geladen: ..\data\pokemon\sprites\0892_Gigantamax_Single_Strike.png
geladen: ..\data\pokemon\sprites\0892_Gigantamax_Rapid_Strike.png

In [3]:
from fpdf import FPDF
from pathlib import Path

import math

out_dir = Path("../data/pokemon/sprites")

# json_path = "../data/pokemon/pokedex_edited.json"
json_path = "../data/pokemon/pokedex_extended_cleaned.json"
df_edited = pd.read_json(json_path, orient="records")

df_edited.iloc[15:25].head()

for k_, pokemon in df_edited.iterrows():
    more_forms = pokemon.get("weitere_erscheinungsformen")
    more_devs = pokemon.get("weitere_entwicklungen")
    all_add_forms = [more_forms, more_devs]
    for forms in all_add_forms:
        if isinstance(forms, list) and len(forms) > 0:
            pokemon_id = int(pokemon["nr"])

            for form in forms:
                sprite_path = out_dir / f"{pokemon_id:04d}_{form['form_name']}.png"
                if not sprite_path.exists():
                    r = requests.get(form["sprite_bulbapedia"], timeout=20)
                    r.raise_for_status()
                    sprite_path.write_bytes(r.content)
                    print(f"geladen: {sprite_path}")


def draw_arrow(pdf, x1, y1, x2, y2, color=(0, 0, 0), line_w=0.2, head_len=1.0, head_angle_deg=45):
    # shaft
    pdf.set_draw_color(*color)
    pdf.set_line_width(line_w)
    pdf.line(x1, y1, x2, y2)

    # arrow head (2 short lines)
    ang = math.atan2(y2 - y1, x2 - x1)
    a = math.radians(head_angle_deg)

    x3 = x2 - head_len * math.cos(ang - a)
    y3 = y2 - head_len * math.sin(ang - a)
    x4 = x2 - head_len * math.cos(ang + a)
    y4 = y2 - head_len * math.sin(ang + a)

    pdf.line(x2, y2, x3, y3)
    pdf.line(x2, y2, x4, y4)


H_MARGIN = 20
V_MARGIN = 20

TYPE_ICON_FILE = {
    "Wasser": "Pokemon_Type_Icon_Water@4x.png",
    "Normal": "Pokemon_Type_Icon_Normal@4x.png",
    "Pflanze": "Pokemon_Type_Icon_Grass@4x.png",
    "Käfer": "Pokemon_Type_Icon_Bug@4x.png",
    "Feuer": "Pokemon_Type_Icon_Fire@4x.png",
    "Psycho": "Pokemon_Type_Icon_Psychic@4x.png",
    "Elektro": "Pokemon_Type_Icon_Electric@4x.png",
    "Gestein": "Pokemon_Type_Icon_Rock@4x.png",
    "Unlicht": "Pokemon_Type_Icon_Dark@4x.png",
    "Gift": "Pokemon_Type_Icon_Poison@4x.png",
    "Boden": "Pokemon_Type_Icon_Ground@4x.png",
    "Kampf": "Pokemon_Type_Icon_Fighting@4x.png",
    "Drache": "Pokemon_Type_Icon_Dragon@4x.png",
    "Stahl": "Pokemon_Type_Icon_Steel@4x.png",
    "Geist": "Pokemon_Type_Icon_Ghost@4x.png",
    "Eis": "Pokemon_Type_Icon_Ice@4x.png",
    "Fee": "Pokemon_Type_Icon_Fairy@4x.png",
    "Flug": "Pokemon_Type_Icon_Flying@4x.png",
}


pdf = FPDF(format='A4')
pdf.set_margins(left=H_MARGIN, top=40, right=H_MARGIN)
pdf.add_font(family='Pokemon',fname=f'../data/pokemon/pokemon-ds-font.ttf',uni=True)
pdf.add_font(family='Lato',fname=f'../data/pokemon/Lato-Regular.ttf',uni=True)
pdf.add_font(family='Lato',fname=f'../data/pokemon/Lato-Bold.ttf',uni=True, style="B")
pdf.set_auto_page_break(auto=False)


def draw_pokemon_card(pdf, x, y, width, height, pokemon, sprite_path, alternative_form=False):
#     pdf.set_font("Arial", "B", 16)
#     pdf.cell(0, 10, f"{pokemon['nr']:03d} - {pokemon['name_de']}", ln=True)

    k_shift = 1
    CARD_PADDING = 10
    card_width = width - 2 * CARD_PADDING

    TEXT_SHIFT = 30

    if sprite_path.exists():
        pdf.image(str(sprite_path), x=x + CARD_PADDING, y=y + CARD_PADDING, w=card_width)

    icon_size = card_width / 7

    types = []
    if pokemon['typ1']:
        if pokemon['typ1'] in TYPE_ICON_FILE:
            types.append(pokemon['typ1'])
    if pokemon['typ2']:
        if pokemon['typ2'] in TYPE_ICON_FILE:
            types.append(pokemon['typ2'])

    icon_dir = "../data/pokemon/icons"
    for t in types:
        icon_x = x + width/2 - (len(types) * icon_size)/2 + types.index(t)*icon_size
        icon_y = y + height - TEXT_SHIFT - 1 - icon_size
        icon_file = TYPE_ICON_FILE.get(t)

        if icon_file is not None:
            pdf.image(f"{icon_dir}/{icon_file}", x=icon_x, y=icon_y, w=icon_size*0.9)

    if alternative_form:
        pdf.set_xy(x + CARD_PADDING, y + height - TEXT_SHIFT -1)
        pdf.set_font("Lato", "", 14)
        pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")

    pdf.set_xy(x + CARD_PADDING, y + height - TEXT_SHIFT + 6)
    pdf.set_font("Lato", "B", 14)
    pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

    if not alternative_form:
        pdf.set_xy(x + CARD_PADDING, y + height - TEXT_SHIFT -1)
        pdf.set_font("Lato", "", 21)
        pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")

        
    
        # print(pokemon['entwicklungsabfolge_nr'])

        

        # print(pokemon['entwicklungsabfolge_nr'])

        next_evo_card_count = 6


        x_offset = 0
        y_offset = 0
        for j, evo_seq in enumerate(pokemon['entwicklungsabfolge_nr']):
            # y_offset = j * (icon_size + 5)

            if j >= 2:
                x_offset = (math.floor((j-2) / next_evo_card_count) + 1) * width
                if (j-2) % next_evo_card_count == 0:
                    k_shift += 1
                    y_offset = -(icon_size + 5) * (next_evo_card_count-2)
                    if x+x_offset > pdf.w - width - H_MARGIN:
                        y_offset += height

                if x+x_offset > pdf.w - width - H_MARGIN:
                    x_offset = -2*(width)

            for i, evo_nr in enumerate(evo_seq):
                # if i >= 3:
                #     break
                # evo_name = df_edited[df_edited["nr"] == evo_nr]["name_de"].values[0]
                # pdf.set_xy(x + CARD_PADDING, y + height - 12 + i*4)
                # pdf.set_font("Lato", "", 10)
                # pdf.cell(w=card_width, h=4, txt=f"{evo_nr:03d} - {evo_name}", ln=True, align="C")
                evo_path = out_dir / f"{evo_nr:04d}.png"
                
                evo_width = card_width / 3
                evo_x = x + x_offset + CARD_PADDING + card_width/2 - ((len(evo_seq)-0.5) * evo_width)/2 + i*evo_width
                if evo_path.exists():
                    pdf.image(str(evo_path), 
                            x=evo_x, 
                            y=y + height - TEXT_SHIFT + y_offset + 15, w=evo_width*0.5)
                
                pdf.set_xy(evo_x, y + height - TEXT_SHIFT + y_offset + 18 + evo_width*0.25)
                pdf.set_font("Lato", "", 8)
                if evo_nr < 9000:
                    pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

                if i > 0:
                    draw_arrow(pdf, 
                            evo_x - evo_width*0.3, y + height - TEXT_SHIFT + y_offset + 15 + evo_width*0.3, 
                            evo_x - evo_width*0.1, y + height - TEXT_SHIFT + y_offset + 15 + evo_width*0.3)
            
            y_offset += icon_size + 5

    return k_shift


COLS = 3
ROWS = 3

# for k, pokemon in df.head(151).iterrows():
k = 0
# for k_, pokemon in df_edited.iloc[129:140].iterrows():

# for k_, pokemon in df_edited.iloc[0:151].iterrows(): # Kanto
# for k_, pokemon in df_edited.iloc[151:251].iterrows(): # Johto
# for k_, pokemon in df_edited.iloc[251:386].iterrows(): # Hoenn
# for k_, pokemon in df_edited.iloc[386:493].iterrows(): # Sinnoh
# for k_, pokemon in df_edited.iloc[493:649].iterrows(): # Einall
# for k_, pokemon in df_edited.iloc[649:721].iterrows(): # Kalos
# for k_, pokemon in df_edited.iloc[721:807].iterrows(): # Alola
# for k_, pokemon in df_edited.iloc[807:809].iterrows(): # Unknown
for k_, pokemon in df_edited.iloc[809:898].iterrows(): # Galar
# for k_, pokemon in df_edited.iloc[898:905].iterrows(): # Hisui
# for k_, pokemon in df_edited.iloc[905:1025].iterrows(): # Paldea

    pokemon_id = int(pokemon["nr"])
    sprite_path = out_dir / f"{pokemon_id:04d}.png"

    if k%(COLS*ROWS) == 0:
        pdf.add_page()

    i = (k % (COLS * ROWS)) % COLS
    j = (k % (COLS * ROWS)) // COLS

    print(k, i, j, sprite_path)

    x = H_MARGIN + i * (pdf.w - 2 * H_MARGIN) / COLS
    y = V_MARGIN + j * (pdf.h - 2 * V_MARGIN) / ROWS

    card_width = (pdf.w - 2 * H_MARGIN) / COLS
    card_height = (pdf.h - 2 * V_MARGIN) / ROWS

    k = k + draw_pokemon_card(pdf, x, y, width=card_width, height=card_height, pokemon=pokemon, sprite_path=sprite_path)
    
    
    # forms = pokemon.get("weitere_erscheinungsformen")

    more_forms = pokemon.get("weitere_erscheinungsformen")
    more_devs = pokemon.get("weitere_entwicklungen")
    all_add_forms = [more_forms, more_devs]
    for forms in all_add_forms:

        if isinstance(forms, list) and len(forms) > 0:
            for form in forms:

                form_sprite_path = out_dir / f"{int(pokemon['nr']):04d}_{form['form_name']}.png"

                if k%(COLS*ROWS) == 0:
                    pdf.add_page()

                i = (k % (COLS * ROWS)) % COLS
                j = (k % (COLS * ROWS)) // COLS

                print(k, i, j, form_sprite_path)

                x = H_MARGIN + i * (pdf.w - 2 * H_MARGIN) / COLS
                y = V_MARGIN + j * (pdf.h - 2 * V_MARGIN) / ROWS

                pokemon_form = pokemon.copy()
                pokemon_form["form_name"] = form['form_name'].capitalize()
                if "typ1" in form and pd.notna(form["typ1"]):
                    pokemon_form["typ1"] = form["typ1"]
                if "typ2" in form and pd.notna(form["typ2"]):
                    pokemon_form["typ2"] = form["typ2"]

                k = k + draw_pokemon_card(pdf, x, y, width=card_width, height=card_height, pokemon=pokemon_form, sprite_path=form_sprite_path, alternative_form=True)

full_path = "../data/pokemon/pokedex_edited.pdf"
pdf.output(full_path, 'F')

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:77: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family='Pokemon',fname=f'../data/pokemon/pokemon-ds-font.ttf',uni=True)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:78: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family='Lato',fname=f'../data/pokemon/Lato-Regular.ttf',uni=True)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:79: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family='Lato',fname=f'../data/pokemon/Lato-Bold.ttf',uni=True, style="B")

0 0 0 ..\data\pokemon\sprites\0810.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

1 1 0 ..\data\pokemon\sprites\0811.png
2 2 0 ..\data\pokemon\sprites\0812.png
3 0 1 ..\data\pokemon\sprites\0812_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

4 1 1 ..\data\pokemon\sprites\0813.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

5 2 1 ..\data\pokemon\sprites\0814.png
6 0 2 ..\data\pokemon\sprites\0815.png
7 1 2 ..\data\pokemon\sprites\0815_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

8 2 2 ..\data\pokemon\sprites\0816.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

9 0 0 ..\data\pokemon\sprites\0817.png
10 1 0 ..\data\pokemon\sprites\0818.png
11 2 0 ..\data\pokemon\sprites\0818_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

12 0 1 ..\data\pokemon\sprites\0819.png
13 1 1 ..\data\pokemon\sprites\0820.png
14 2 1 ..\data\pokemon\sprites\0821.png
15 0 2 ..\data\pokemon\sprites\0822.png
16 1 2 ..\data\pokemon\sprites\0823.png
17 2 2 ..\data\pokemon\sprites\0823_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

18 0 0 ..\data\pokemon\sprites\0824.png
19 1 0 ..\data\pokemon\sprites\0825.png
20 2 0 ..\data\pokemon\sprites\0826.png
21 0 1 ..\data\pokemon\sprites\0826_Gigantamax.png
22 1 1 ..\data\pokemon\sprites\0827.png
23 2 1 ..\data\pokemon\sprites\0828.png
24 0 2 ..\data\pokemon\sprites\0829.png
25 1 2 ..\data\pokemon\sprites\0830.png
26 2 2 ..\data\pokemon\sprites\0831.png
27 0 0 ..\data\pokemon\sprites\0832.png
28 1 0 ..\data\pokemon\sprites\0833.png
29 2 0 ..\data\pokemon\sprites\0834.png
30 0 1 ..\data\pokemon\sprites\0834_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

31 1 1 ..\data\pokemon\sprites\0835.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

32 2 1 ..\data\pokemon\sprites\0836.png
33 0 2 ..\data\pokemon\sprites\0837.png
34 1 2 ..\data\pokemon\sprites\0838.png
35 2 2 ..\data\pokemon\sprites\0839.png
36 0 0 ..\data\pokemon\sprites\0839_Gigantamax.png
37 1 0 ..\data\pokemon\sprites\0840.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

39 0 1 ..\data\pokemon\sprites\0841.png
40 1 1 ..\data\pokemon\sprites\0841_Gigantamax.png
41 2 1 ..\data\pokemon\sprites\0842.png
42 0 2 ..\data\pokemon\sprites\0843.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

43 1 2 ..\data\pokemon\sprites\0844.png
44 2 2 ..\data\pokemon\sprites\0844_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

45 0 0 ..\data\pokemon\sprites\0845.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

46 1 0 ..\data\pokemon\sprites\0846.png
47 2 0 ..\data\pokemon\sprites\0847.png
48 0 1 ..\data\pokemon\sprites\0848.png
49 1 1 ..\data\pokemon\sprites\0849.png
50 2 1 ..\data\pokemon\sprites\0849_Low_Key.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

51 0 2 ..\data\pokemon\sprites\0849_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

52 1 2 ..\data\pokemon\sprites\0850.png
53 2 2 ..\data\pokemon\sprites\0851.png
54 0 0 ..\data\pokemon\sprites\0851_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

55 1 0 ..\data\pokemon\sprites\0852.png
56 2 0 ..\data\pokemon\sprites\0853.png
57 0 1 ..\data\pokemon\sprites\0854.png
58 1 1 ..\data\pokemon\sprites\0855.png
59 2 1 ..\data\pokemon\sprites\0856.png
60 0 2 ..\data\pokemon\sprites\0857.png
61 1 2 ..\data\pokemon\sprites\0858.png
62 2 2 ..\data\pokemon\sprites\0858_Gigantamax.png
63 0 0 ..\data\pokemon\sprites\0859.png
64 1 0 ..\data\pokemon\sprites\0860.png
65 2 0 ..\data\pokemon\sprites\0861.png
66 0 1 ..\data\pokemon\sprites\0861_Gigantamax.png
67 1 1 ..\data\pokemon\sprites\0862.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

68 2 1 ..\data\pokemon\sprites\0863.png
69 0 2 ..\data\pokemon\sprites\0864.png
70 1 2 ..\data\pokemon\sprites\0865.png
71 2 2 ..\data\pokemon\sprites\0866.png
72 0 0 ..\data\pokemon\sprites\0867.png
73 1 0 ..\data\pokemon\sprites\0868.png
74 2 0 ..\data\pokemon\sprites\0869.png
75 0 1 ..\data\pokemon\sprites\0869_Gigantamax.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

76 1 1 ..\data\pokemon\sprites\0870.png
77 2 1 ..\data\pokemon\sprites\0870_Mega.png
78 0 2 ..\data\pokemon\sprites\0871.png
79 1 2 ..\data\pokemon\sprites\0872.png
80 2 2 ..\data\pokemon\sprites\0873.png
81 0 0 ..\data\pokemon\sprites\0874.png
82 1 0 ..\data\pokemon\sprites\0875.png
83 2 0 ..\data\pokemon\sprites\0875_Noice.png
84 0 1 ..\data\pokemon\sprites\0876.png
85 1 1 ..\data\pokemon\sprites\0876_Female.png
86 2 1 ..\data\pokemon\sprites\0877.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")

87 0 2 ..\data\pokemon\sprites\0877_Hangry.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")

88 1 2 ..\data\pokemon\sprites\0878.png
89 2 2 ..\data\pokemon\sprites\0879.png
90 0 0 ..\data\pokemon\sprites\0879_Gigantamax.png
91 1 0 ..\data\pokemon\sprites\0880.png
92 2 0 ..\data\pokemon\sprites\0881.png
93 0 1 ..\data\pokemon\sprites\0882.png
94 1 1 ..\data\pokemon\sprites\0883.png
95 2 1 ..\data\pokemon\sprites\0884.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

96 0 2 ..\data\pokemon\sprites\0884_Gigantamax.png
97 1 2 ..\data\pokemon\sprites\0885.png
98 2 2 ..\data\pokemon\sprites\0886.png
99 0 0 ..\data\pokemon\sprites\0887.png
100 1 0 ..\data\pokemon\sprites\0888.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:175: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=evo_width*0.6, h=4, txt=f"{evo_nr:04d}", ln=True, align="C")

101 2 0 ..\data\pokemon\sprites\0889.png
102 0 1 ..\data\pokemon\sprites\0890.png
103 1 1 ..\data\pokemon\sprites\0891.png
104 2 1 ..\data\pokemon\sprites\0892.png
105 0 2 ..\data\pokemon\sprites\0892_Rapid_Strike.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

106 1 2 ..\data\pokemon\sprites\0892_Gigantamax_Single_Strike.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

107 2 2 ..\data\pokemon\sprites\0892_Gigantamax_Rapid_Strike.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

108 0 0 ..\data\pokemon\sprites\0893.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

109 1 0 ..\data\pokemon\sprites\0893_Dada.png
110 2 0 ..\data\pokemon\sprites\0894.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:127: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['nr']:04d}", ln=True, align="C")

111 0 1 ..\data\pokemon\sprites\0895.png
112 1 1 ..\data\pokemon\sprites\0896.png
113 2 1 ..\data\pokemon\sprites\0897.png
114 0 2 ..\data\pokemon\sprites\0898.png
115 1 2 ..\data\pokemon\sprites\0898_Ice_Rider.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")

116 2 2 ..\data\pokemon\sprites\0898_Shadow_Rider.png

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:118: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['form_name']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:122: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  pdf.cell(w=card_width, h=10, txt=f"{pokemon['name_de']}", ln=True, align="C")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_21448\1731450811.py:259: DeprecationWarning: "dest" parameter is deprecated since v2.2.0, unused and will soon be removed
  pdf.output(full_path, 'F')

In [22]:
from fpdf import FPDF
from pathlib import Path
import pandas as pd

json_path = Path("../data/pokemon/pokedex_edited.json")
if not json_path.exists():
    raise FileNotFoundError(f"Datei nicht gefunden: {json_path.resolve()}")

df_edited = pd.read_json(json_path, orient="records")
df_edited_sorted = df_edited.sort_values("name_de", key=lambda s: s.str.lower()).reset_index(drop=True)

print(df_edited_sorted.head())

H_MARGIN = 20

pdf = FPDF(format="A4")
pdf.set_margins(left=H_MARGIN, top=20, right=H_MARGIN)
pdf.add_font(family="Pokemon", fname="../data/pokemon/pokemon-ds-font.ttf", uni=True)
pdf.add_font(family="Lato", fname="../data/pokemon/Lato-Regular.ttf", uni=True)
pdf.add_font(family="Lato", fname="../data/pokemon/Lato-Bold.ttf", uni=True, style="B")
pdf.set_auto_page_break(auto=False)
pdf.add_page()

# 3-column layout settings
COLS = 3
COL_GAP = 4.0
TOP_Y = 20.0
BOTTOM_Y = pdf.h - 20.0
line_h = 9.0
header_h = 12.0

usable_w = pdf.w - 2 * H_MARGIN
col_w = (usable_w - (COLS - 1) * COL_GAP) / COLS

col_idx = 0
y = TOP_Y


def col_x(idx):
    return H_MARGIN + idx * (col_w + COL_GAP)


def next_column_or_page():
    global col_idx, y
    col_idx += 1
    if col_idx >= COLS:
        pdf.add_page()
        col_idx = 0
    y = TOP_Y


def ensure_space(required_height):
    global y
    if y + required_height > BOTTOM_Y:
        next_column_or_page()


def write_text_line(text, bold=False, size=10):
    global y
    pdf.set_xy(col_x(col_idx), y)
    pdf.set_font("Lato", "B" if bold else "", size)
    pdf.cell(w=col_w, h=line_h, txt=text, ln=0)
    y += line_h

def write_text_line_with_sprite(text, sprite_path, bold=False, size=10, line_height=line_h):
    global y
    pdf.set_xy(col_x(col_idx), y)

    if sprite_path is not None and sprite_path.exists():
        pdf.image(str(sprite_path), w=8)

    
    pdf.set_xy(col_x(col_idx)+8, y)

    pdf.set_font("Lato", "B" if bold else "", size)
    pdf.cell(w=col_w, h=line_height, txt=text, ln=0)
    y += line_height


current_letter = None
for _, row in df_edited_sorted.iterrows():
    name = str(row["name_de"]) if pd.notna(row["name_de"]) else ""
    region = str(row["region"]) if pd.notna(row["region"]) else ""
    first_letter = name[:1].upper() if name else "#"

    if first_letter != current_letter:
        current_letter = first_letter
        
        ensure_space(header_h + line_h)
        write_text_line(f"", bold=True, size=21)

        ensure_space(header_h + line_h)
        write_text_line(f"{current_letter}", bold=True, size=21)

    ensure_space(line_h)
    
    # write_text_line(f"{int(row['nr']):04d} {name}", bold=False, size=14)
    sprite_path = Path(f"../data/pokemon/sprites/{int(row['nr']):04d}.png")
    write_text_line_with_sprite(f"{int(row['nr']):04d}  {name}", sprite_path, bold=False, size=11)
    y -= 1
    # write_text_line_with_sprite(f"            {region}", None, bold=False, size=9, line_height=0)
    write_text_line_with_sprite(f"{region}", None, bold=False, size=7, line_height=0)


full_path = "../data/pokemon/pokedex_abc_index.pdf"
pdf.output(full_path, "F")
print(f"PDF gespeichert: {full_path}")

    nr   name_de     name_en     typ1     typ2  region generation  \
0  367  Aalabyss     Huntail   Wasser     None   Hoenn        III
1   63      Abra        Abra   Psycho     None   Kanto          I
2  359     Absol       Absol  Unlicht     None   Hoenn        III
3  962    Adebom  Bombirdier     Flug  Unlicht  Paldea         IX
4  503   Admurai    Samurott   Wasser     None   Unova          V

   entwicklungsstufe entwickelt_aus_en  \
0                  1          clamperl
1                  0              None
2                  0              None
3                  0              None
4                  2            dewott

                                          sprite_url  \
0  https://raw.githubusercontent.com/PokeAPI/spri...
1  https://raw.githubusercontent.com/PokeAPI/spri...
2  https://raw.githubusercontent.com/PokeAPI/spri...
3  https://raw.githubusercontent.com/PokeAPI/spri...
4  https://raw.githubusercontent.com/PokeAPI/spri...

                                   sprite_bulbapedia entwicklungsabfolge_nr  \
0  https://archives.bulbagarden.net/media/upload/...           [[366, 367]]
1  https://archives.bulbagarden.net/media/upload/...         [[63, 64, 65]]
2  https://archives.bulbagarden.net/media/upload/...                   [[]]
3  https://archives.bulbagarden.net/media/upload/...                   [[]]
4  https://archives.bulbagarden.net/media/upload/...      [[501, 502, 503]]

  weitere_entwicklungen weitere_erscheinungsformen
0                   NaN                        NaN
1                   NaN                        NaN
2                   NaN                        NaN
3                   NaN                        NaN
4                   NaN                        NaN

C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:18: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family="Pokemon", fname="../data/pokemon/pokemon-ds-font.ttf", uni=True)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:19: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family="Lato", fname="../data/pokemon/Lato-Regular.ttf", uni=True)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:20: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  pdf.add_font(family="Lato", fname="../data/pokemon/Lato-Bold.ttf", uni=True, style="B")
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:62: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=col_w, h=line_h, txt=text, ln=0)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:62: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=0 use new_x=XPos.RIGHT, new_y=YPos.TOP.
  pdf.cell(w=col_w, h=line_h, txt=text, ln=0)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:76: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  pdf.cell(w=col_w, h=line_height, txt=text, ln=0)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:76: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=0 use new_x=XPos.RIGHT, new_y=YPos.TOP.
  pdf.cell(w=col_w, h=line_height, txt=text, ln=0)
C:\Users\ruedi.luethi\AppData\Local\Temp\ipykernel_16996\2889806526.py:106: DeprecationWarning: "dest" parameter is deprecated since v2.2.0, unused and will soon be removed
  pdf.output(full_path, "F")

PDF gespeichert: ../data/pokemon/pokedex_abc_index.pdf

In [1]:
from pathlib import Path
from urllib.parse import urljoin, unquote
import re
import requests
import pandas as pd

BASE_URL = "https://bulbapedia.bulbagarden.net"
html_path = Path("../data/pokemon/bulpedia_list.html")

if not html_path.exists():
    raise FileNotFoundError(f"Datei nicht gefunden: {html_path.resolve()}")

html = html_path.read_text(encoding="utf-8", errors="ignore")

# Alle href="/wiki/..." oder href='/wiki/...' extrahieren
pattern = r"href\s*=\s*[\"'](/wiki/[^\"'#?]+)[\"']"
matches = re.findall(pattern, html)

# Deduplizieren, Reihenfolge beibehalten
wiki_links = list(dict.fromkeys(matches))
print(f"Gefundene /wiki/-Links: {len(wiki_links)}")

def extract_table_block(page_html: str, start_pos: int) -> str:
    """Extrahiert den kompletten <table>...</table>-Block inklusive verschachtelter Tabellen."""
    tag_re = re.compile(r"</?table\b[^>]*>", re.IGNORECASE)
    depth = 0

    for m in tag_re.finditer(page_html, pos=start_pos):
        tag = m.group(0).lower()
        if tag.startswith("</table"):
            depth -= 1
            if depth == 0:
                return page_html[start_pos:m.end()]
        else:
            depth += 1

    return ""

def find_roundy_infobox(page_html: str) -> str:
    """Findet die erste Tabelle mit den Klassen 'roundy' und 'infobox'."""
    table_start_re = re.compile(
        r"<table\b[^>]*class\s*=\s*([\"'])([^\"']*)\1[^>]*>",
        re.IGNORECASE,
    )

    for m in table_start_re.finditer(page_html):
        classes = m.group(2).lower()
        if "roundy" in classes and "infobox" in classes:
            return extract_table_block(page_html, m.start())

    return ""

def extract_file_links_from_infobox(infobox_html: str) -> list[str]:
    """Extrahiert /wiki/File:... Links aus der Infobox in Original-Reihenfolge, ohne Duplikate."""
    file_link_re = re.compile(
        r"<a\b[^>]*href\s*=\s*[\"'](/wiki/File:[^\"'#?]+)[\"'][^>]*>",
        re.IGNORECASE,
    )
    links = file_link_re.findall(infobox_html)
    return list(dict.fromkeys(links))

def file_stem_from_wiki_file_link(link: str) -> str:
    """/wiki/File:0065Alakazam-Mega.png -> 0065Alakazam-Mega"""
    if not link.startswith("/wiki/File:"):
        return ""
    filename = unquote(link[len("/wiki/File:"):])
    return filename.rsplit(".", 1)[0]

def select_relevant_other_thumbnails(main_thumbnail: str, other_thumbnails: list[str]) -> list[str]:
    """
    Liefert alle relevanten Zusatzformen (nicht nur die erste).
    Heuristik: Zusatzbild muss den gleichen Basisstamm wie das Hauptbild haben
    und danach einen Trenner '-' oder '_' tragen (z.B. -Mega, -Gmax, -Alola).
    """
    if not main_thumbnail or not other_thumbnails:
        return []

    main_stem = file_stem_from_wiki_file_link(main_thumbnail)
    if not main_stem:
        return []

    # Basisstamm: vor erster Form-Erweiterung abschneiden
    # z.B. 0025Pikachu-Gmax -> 0025Pikachu
    main_base = re.split(r"[-_]", main_stem, maxsplit=1)[0]

    relevant = []
    for link in other_thumbnails:
        stem = file_stem_from_wiki_file_link(link)
        if not stem:
            continue

        if stem.startswith(main_base + "-") or stem.startswith(main_base + "_"):
            relevant.append(link)

    return relevant

session = requests.Session()
session.headers.update({"User-Agent": "Mozilla/5.0 (compatible; pokedex-form-scan/1.0)"})

results = []
errors = []

# Optional: zum schnellen Testen limitieren (z.B. 100). None = alle Links
SAMPLE_LIMIT = None
links_to_process = wiki_links if SAMPLE_LIMIT is None else wiki_links[:SAMPLE_LIMIT]

for idx, wiki_path in enumerate(links_to_process, start=1):
    page_url = urljoin(BASE_URL, wiki_path)

    try:
        resp = session.get(page_url, timeout=20)
        resp.raise_for_status()
        page_html = resp.text
    except Exception as e:
        errors.append({"wiki_path": wiki_path, "error": str(e)})
        continue

    infobox_html = find_roundy_infobox(page_html)
    if not infobox_html:
        continue

    file_links = extract_file_links_from_infobox(infobox_html)
    if not file_links:
        continue

    main_thumbnail = file_links[0]
    other_thumbnails = file_links[1:]
    relevant_others = select_relevant_other_thumbnails(main_thumbnail, other_thumbnails)

    print(main_thumbnail, relevant_others)

    results.append(
        {
            "wiki_path": wiki_path,
            "wiki_url": page_url,
            "main_thumbnail": main_thumbnail,
            "main_thumbnail_url": urljoin(BASE_URL, main_thumbnail),
            "relevant_other_thumbnails": relevant_others,
            "relevant_other_thumbnail_urls": [urljoin(BASE_URL, p) for p in relevant_others],
            "all_other_thumbnails": other_thumbnails,
        }
    )

    if idx % 50 == 0:
        print(f"Bearbeitet: {idx}/{len(links_to_process)}")

print(f"Seiten mit Infobox-Thumbnails: {len(results)}")
print(f"Fehler beim Laden: {len(errors)}")

forms_df = pd.DataFrame(results)
forms_df.head(20)

c:\Users\ruedi.luethi\.conda\envs\streamlit\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

Gefundene /wiki/-Links: 1195
/wiki/File:PE_Kanto_Map.png []
/wiki/File:JohtoMap.png []
/wiki/File:Hoenn_ORAS.png []
/wiki/File:Sinnoh_BDSP_artwork.png []
/wiki/File:Unova_B2W2_alt.png []
/wiki/File:Kalos_alt.png []
/wiki/File:Alola_USUM_artwork.png []
/wiki/File:Galar_artwork.png []
/wiki/File:Legends_Arceus_Hisui.png []
/wiki/File:Paldea_artwork.png []
/wiki/File:0494Victini.png []
/wiki/File:SilverTitle.png []
/wiki/File:GreenTitle.png []
/wiki/File:0001Bulbasaur.png []
/wiki/File:0002Ivysaur.png []
/wiki/File:0003Venusaur.png ['/wiki/File:0003Venusaur-Mega.png', '/wiki/File:0003Venusaur-Gigantamax.png']
/wiki/File:0004Charmander.png []
/wiki/File:0005Charmeleon.png []
/wiki/File:0006Charizard.png ['/wiki/File:0006Charizard-Mega_X.png', '/wiki/File:0006Charizard-Mega_Y.png', '/wiki/File:0006Charizard-Gigantamax.png']
/wiki/File:0007Squirtle.png []
/wiki/File:0008Wartortle.png []
/wiki/File:0009Blastoise.png ['/wiki/File:0009Blastoise-Mega.png', '/wiki/File:0009Blastoise-Gigantamax.png']
/wiki/File:0010Caterpie.png []
/wiki/File:0011Metapod.png []
/wiki/File:0012Butterfree.png ['/wiki/File:0012Butterfree-Gigantamax.png']
/wiki/File:0013Weedle.png []
/wiki/File:0014Kakuna.png []
/wiki/File:0015Beedrill.png ['/wiki/File:0015Beedrill-Mega.png']
/wiki/File:0016Pidgey.png []
/wiki/File:0017Pidgeotto.png []
/wiki/File:0018Pidgeot.png ['/wiki/File:0018Pidgeot-Mega.png']
/wiki/File:0019Rattata.png ['/wiki/File:0019Rattata-Alola.png']
/wiki/File:0020Raticate.png ['/wiki/File:0020Raticate-Alola.png']
/wiki/File:0021Spearow.png []
/wiki/File:0022Fearow.png []
/wiki/File:0023Ekans.png []
/wiki/File:0024Arbok.png []
/wiki/File:0025Pikachu.png ['/wiki/File:0025Pikachu-Cosplay.png', '/wiki/File:0025Pikachu-Partner_Cap.png', '/wiki/File:0025Pikachu-Gigantamax.png']
/wiki/File:0026Raichu.png ['/wiki/File:0026Raichu-Alola.png', '/wiki/File:0026Raichu-Mega_X.png', '/wiki/File:0026Raichu-Mega_Y.png']
/wiki/File:0027Sandshrew.png ['/wiki/File:0027Sandshrew-Alola.png']
/wiki/File:0028Sandslash.png ['/wiki/File:0028Sandslash-Alola.png']
/wiki/File:0029Nidoran.png []
/wiki/File:0030Nidorina.png []
/wiki/File:0031Nidoqueen.png []
/wiki/File:0032Nidoran.png []
/wiki/File:0033Nidorino.png []
/wiki/File:0034Nidoking.png []
/wiki/File:0035Clefairy.png []
/wiki/File:0036Clefable.png ['/wiki/File:0036Clefable-Mega.png']
/wiki/File:0037Vulpix.png ['/wiki/File:0037Vulpix-Alola.png']
/wiki/File:0038Ninetales.png ['/wiki/File:0038Ninetales-Alola.png']
/wiki/File:0039Jigglypuff.png []
/wiki/File:0040Wigglytuff.png []
/wiki/File:0041Zubat.png []
/wiki/File:0042Golbat.png []
/wiki/File:0043Oddish.png []
/wiki/File:0044Gloom.png []
/wiki/File:0045Vileplume.png []
/wiki/File:0046Paras.png []
/wiki/File:0047Parasect.png []
/wiki/File:0048Venonat.png []
/wiki/File:0049Venomoth.png []
/wiki/File:0050Diglett.png ['/wiki/File:0050Diglett-Alola.png']
/wiki/File:0051Dugtrio.png ['/wiki/File:0051Dugtrio-Alola.png']
/wiki/File:0052Meowth.png ['/wiki/File:0052Meowth-Alola.png', '/wiki/File:0052Meowth-Galar.png', '/wiki/File:0052Meowth-Gigantamax.png']
/wiki/File:0053Persian.png ['/wiki/File:0053Persian-Alola.png']
/wiki/File:0054Psyduck.png []
/wiki/File:0055Golduck.png []
/wiki/File:0056Mankey.png []
/wiki/File:0057Primeape.png []
/wiki/File:0058Growlithe.png ['/wiki/File:0058Growlithe-Hisui.png']
/wiki/File:0059Arcanine.png ['/wiki/File:0059Arcanine-Hisui.png']
/wiki/File:0060Poliwag.png []
/wiki/File:0061Poliwhirl.png []
Bearbeitet: 100/1195
/wiki/File:0062Poliwrath.png []
/wiki/File:0063Abra.png []
/wiki/File:0064Kadabra.png []
/wiki/File:0065Alakazam.png ['/wiki/File:0065Alakazam-Mega.png']
/wiki/File:0066Machop.png []
/wiki/File:0067Machoke.png []
/wiki/File:0068Machamp.png ['/wiki/File:0068Machamp-Gigantamax.png']
/wiki/File:0069Bellsprout.png []
/wiki/File:0070Weepinbell.png []
/wiki/File:0071Victreebel.png ['/wiki/File:0071Victreebel-Mega.png']
/wiki/File:0072Tentacool.png []
/wiki/File:0073Tentacruel.png []
/wiki/File:0074Geodude.png ['/wiki/File:0074Geodude-Alola.png']
/wiki/File:0075Graveler.png ['/wiki/File:0075Graveler-Alola.png']
/wiki/File:0076Golem.png ['/wiki/File:0076Golem-Alola.png']
/wiki/File:0077Ponyta.png ['/wiki/File:0077Ponyta-Galar.png']
/wiki/File:0078Rapidash.png ['/wiki/File:0078Rapidash-Galar.png']
/wiki/File:0079Slowpoke.png ['/wiki/File:0079Slowpoke-Galar.png']
/wiki/File:0080Slowbro.png ['/wiki/File:0080Slowbro-Galar.png', '/wiki/File:0080Slowbro-Mega.png']
/wiki/File:0081Magnemite.png []
/wiki/File:0082Magneton.png []
/wiki/File:0083Farfetch%27d.png ['/wiki/File:0083Farfetch%27d-Galar.png']
/wiki/File:0084Doduo.png []
/wiki/File:0085Dodrio.png []
/wiki/File:0086Seel.png []
/wiki/File:0087Dewgong.png []
/wiki/File:0088Grimer.png ['/wiki/File:0088Grimer-Alola.png']
/wiki/File:0089Muk.png ['/wiki/File:0089Muk-Alola.png']
/wiki/File:0090Shellder.png []
/wiki/File:0091Cloyster.png []
/wiki/File:0092Gastly.png []
/wiki/File:0093Haunter.png []
/wiki/File:0094Gengar.png ['/wiki/File:0094Gengar-Mega.png', '/wiki/File:0094Gengar-Gigantamax.png']
/wiki/File:0095Onix.png []
/wiki/File:0096Drowzee.png []
/wiki/File:0097Hypno.png []
/wiki/File:0098Krabby.png []
/wiki/File:0099Kingler.png ['/wiki/File:0099Kingler-Gigantamax.png']
/wiki/File:0100Voltorb.png ['/wiki/File:0100Voltorb-Hisui.png']
/wiki/File:0101Electrode.png ['/wiki/File:0101Electrode-Hisui.png']
/wiki/File:0102Exeggcute.png []
/wiki/File:0103Exeggutor.png ['/wiki/File:0103Exeggutor-Alola.png']
/wiki/File:0104Cubone.png []
/wiki/File:0105Marowak.png ['/wiki/File:0105Marowak-Alola.png']
/wiki/File:0106Hitmonlee.png []
/wiki/File:0107Hitmonchan.png []
/wiki/File:0108Lickitung.png []
/wiki/File:0109Koffing.png []
Bearbeitet: 150/1195
/wiki/File:0110Weezing.png ['/wiki/File:0110Weezing-Galar.png']
/wiki/File:0111Rhyhorn.png []
/wiki/File:0112Rhydon.png []
/wiki/File:0113Chansey.png []
/wiki/File:0114Tangela.png []
/wiki/File:0115Kangaskhan.png ['/wiki/File:0115Kangaskhan-Mega.png']
/wiki/File:0116Horsea.png []
/wiki/File:0117Seadra.png []
/wiki/File:0118Goldeen.png []
/wiki/File:0119Seaking.png []
/wiki/File:0120Staryu.png []
/wiki/File:0121Starmie.png ['/wiki/File:0121Starmie-Mega.png']
/wiki/File:0122Mr._Mime.png ['/wiki/File:0122Mr._Mime-Galar.png']
/wiki/File:0123Scyther.png []
/wiki/File:0124Jynx.png []
/wiki/File:0125Electabuzz.png []
/wiki/File:0126Magmar.png []
/wiki/File:0127Pinsir.png ['/wiki/File:0127Pinsir-Mega.png']
/wiki/File:0128Tauros.png ['/wiki/File:0128Tauros-Paldea_Combat.png', '/wiki/File:0128Tauros-Paldea_Blaze.png', '/wiki/File:0128Tauros-Paldea_Aqua.png']
/wiki/File:0129Magikarp.png []
/wiki/File:0130Gyarados.png ['/wiki/File:0130Gyarados-Mega.png']
/wiki/File:0131Lapras.png ['/wiki/File:0131Lapras-Gigantamax.png']
/wiki/File:0132Ditto.png []
/wiki/File:0133Eevee.png ['/wiki/File:0133Eevee-Gigantamax.png']
/wiki/File:0134Vaporeon.png []
/wiki/File:0135Jolteon.png []
/wiki/File:0136Flareon.png []
/wiki/File:0137Porygon.png []
/wiki/File:0138Omanyte.png []
/wiki/File:0139Omastar.png []
/wiki/File:0140Kabuto.png []
/wiki/File:0141Kabutops.png []
/wiki/File:0142Aerodactyl.png ['/wiki/File:0142Aerodactyl-Mega.png']
/wiki/File:0143Snorlax.png ['/wiki/File:0143Snorlax-Gigantamax.png']
/wiki/File:0144Articuno.png ['/wiki/File:0144Articuno-Galar.png']
/wiki/File:0145Zapdos.png ['/wiki/File:0145Zapdos-Galar.png']
/wiki/File:0146Moltres.png ['/wiki/File:0146Moltres-Galar.png']
/wiki/File:0147Dratini.png []
/wiki/File:0148Dragonair.png []
/wiki/File:0149Dragonite.png ['/wiki/File:0149Dragonite-Mega.png']
/wiki/File:0150Mewtwo.png ['/wiki/File:0150Mewtwo-Mega_X.png', '/wiki/File:0150Mewtwo-Mega_Y.png']
/wiki/File:0151Mew.png []
/wiki/File:0152Chikorita.png []
/wiki/File:0153Bayleef.png []
/wiki/File:0154Meganium.png ['/wiki/File:0154Meganium-Mega.png']
/wiki/File:0155Cyndaquil.png []
/wiki/File:0156Quilava.png []
/wiki/File:0157Typhlosion.png ['/wiki/File:0157Typhlosion-Hisui.png']
/wiki/File:0158Totodile.png []
/wiki/File:0159Croconaw.png []
Bearbeitet: 200/1195
/wiki/File:0160Feraligatr.png ['/wiki/File:0160Feraligatr-Mega.png']
/wiki/File:0161Sentret.png []
/wiki/File:0162Furret.png []
/wiki/File:0163Hoothoot.png []
/wiki/File:0164Noctowl.png []
/wiki/File:0165Ledyba.png []
/wiki/File:0166Ledian.png []
/wiki/File:0167Spinarak.png []
/wiki/File:0168Ariados.png []
/wiki/File:0169Crobat.png []
/wiki/File:0170Chinchou.png []
/wiki/File:0171Lanturn.png []
/wiki/File:0172Pichu.png []
/wiki/File:0173Cleffa.png []
/wiki/File:0174Igglybuff.png []
/wiki/File:0175Togepi.png []
/wiki/File:0176Togetic.png []
/wiki/File:0177Natu.png []
/wiki/File:0178Xatu.png []
/wiki/File:0179Mareep.png []
/wiki/File:0180Flaaffy.png []
/wiki/File:0181Ampharos.png ['/wiki/File:0181Ampharos-Mega.png']
/wiki/File:0182Bellossom.png []
/wiki/File:0183Marill.png []
/wiki/File:0184Azumarill.png []
/wiki/File:0185Sudowoodo.png []
/wiki/File:0186Politoed.png []
/wiki/File:0187Hoppip.png []
/wiki/File:0188Skiploom.png []
/wiki/File:0189Jumpluff.png []
/wiki/File:0190Aipom.png []
/wiki/File:0191Sunkern.png []
/wiki/File:0192Sunflora.png []
/wiki/File:0193Yanma.png []
/wiki/File:0194Wooper.png ['/wiki/File:0194Wooper-Paldea.png']
/wiki/File:0195Quagsire.png []
/wiki/File:0196Espeon.png []
/wiki/File:0197Umbreon.png []
/wiki/File:0198Murkrow.png []
/wiki/File:0199Slowking.png ['/wiki/File:0199Slowking-Galar.png']
/wiki/File:0200Misdreavus.png []
/wiki/File:0201Unown.png []
/wiki/File:0202Wobbuffet.png []
/wiki/File:0203Girafarig.png []
/wiki/File:0204Pineco.png []
/wiki/File:0205Forretress.png []
/wiki/File:0206Dunsparce.png []
/wiki/File:0207Gligar.png []
/wiki/File:0208Steelix.png ['/wiki/File:0208Steelix-Mega.png']
/wiki/File:0209Snubbull.png []
Bearbeitet: 250/1195
/wiki/File:0210Granbull.png []
/wiki/File:0211Qwilfish.png ['/wiki/File:0211Qwilfish-Hisui.png']
/wiki/File:0212Scizor.png ['/wiki/File:0212Scizor-Mega.png']
/wiki/File:0213Shuckle.png []
/wiki/File:0214Heracross.png ['/wiki/File:0214Heracross-Mega.png']
/wiki/File:0215Sneasel.png ['/wiki/File:0215Sneasel-Hisui.png']
/wiki/File:0216Teddiursa.png []
/wiki/File:0217Ursaring.png []
/wiki/File:0218Slugma.png []
/wiki/File:0219Magcargo.png []
/wiki/File:0220Swinub.png []
/wiki/File:0221Piloswine.png []
/wiki/File:0222Corsola.png ['/wiki/File:0222Corsola-Galar.png']
/wiki/File:0223Remoraid.png []
/wiki/File:0224Octillery.png []
/wiki/File:0225Delibird.png []
/wiki/File:0226Mantine.png []
/wiki/File:0227Skarmory.png ['/wiki/File:0227Skarmory-Mega.png']
/wiki/File:0228Houndour.png []
/wiki/File:0229Houndoom.png ['/wiki/File:0229Houndoom-Mega.png']
/wiki/File:0230Kingdra.png []
/wiki/File:0231Phanpy.png []
/wiki/File:0232Donphan.png []
/wiki/File:0233Porygon2.png []
/wiki/File:0234Stantler.png []
/wiki/File:0235Smeargle.png []
/wiki/File:0236Tyrogue.png []
/wiki/File:0237Hitmontop.png []
/wiki/File:0238Smoochum.png []
/wiki/File:0239Elekid.png []
/wiki/File:0240Magby.png []
/wiki/File:0241Miltank.png []
/wiki/File:0242Blissey.png []
/wiki/File:0243Raikou.png []
/wiki/File:0244Entei.png []
/wiki/File:0245Suicune.png []
/wiki/File:0246Larvitar.png []
/wiki/File:0247Pupitar.png []
/wiki/File:0248Tyranitar.png ['/wiki/File:0248Tyranitar-Mega.png']
/wiki/File:0249Lugia.png []
/wiki/File:0250Ho-Oh.png []
/wiki/File:0251Celebi.png []
/wiki/File:FireRedTitle.png []
/wiki/File:0252Treecko.png []
/wiki/File:0253Grovyle.png []
/wiki/File:0254Sceptile.png ['/wiki/File:0254Sceptile-Mega.png']
/wiki/File:0255Torchic.png []
/wiki/File:0256Combusken.png []
/wiki/File:0257Blaziken.png ['/wiki/File:0257Blaziken-Mega.png']
/wiki/File:0258Mudkip.png []
Bearbeitet: 300/1195
/wiki/File:0259Marshtomp.png []
/wiki/File:0260Swampert.png ['/wiki/File:0260Swampert-Mega.png']
/wiki/File:0261Poochyena.png []
/wiki/File:0262Mightyena.png []
/wiki/File:0263Zigzagoon.png ['/wiki/File:0263Zigzagoon-Galar.png']
/wiki/File:0264Linoone.png ['/wiki/File:0264Linoone-Galar.png']
/wiki/File:0265Wurmple.png []
/wiki/File:0266Silcoon.png []
/wiki/File:0267Beautifly.png []
/wiki/File:0268Cascoon.png []
/wiki/File:0269Dustox.png []
/wiki/File:0270Lotad.png []
/wiki/File:0271Lombre.png []
/wiki/File:0272Ludicolo.png []
/wiki/File:0273Seedot.png []
/wiki/File:0274Nuzleaf.png []
/wiki/File:0275Shiftry.png []
/wiki/File:0276Taillow.png []
/wiki/File:0277Swellow.png []
/wiki/File:0278Wingull.png []
/wiki/File:0279Pelipper.png []
/wiki/File:0280Ralts.png []
/wiki/File:0281Kirlia.png []
/wiki/File:0282Gardevoir.png ['/wiki/File:0282Gardevoir-Mega.png']
/wiki/File:0283Surskit.png []
/wiki/File:0284Masquerain.png []
/wiki/File:0285Shroomish.png []
/wiki/File:0286Breloom.png []
/wiki/File:0287Slakoth.png []
/wiki/File:0288Vigoroth.png []
/wiki/File:0289Slaking.png []
/wiki/File:0290Nincada.png []
/wiki/File:0291Ninjask.png []
/wiki/File:0292Shedinja.png []
/wiki/File:0293Whismur.png []
/wiki/File:0294Loudred.png []
/wiki/File:0295Exploud.png []
/wiki/File:0296Makuhita.png []
/wiki/File:0297Hariyama.png []
/wiki/File:0298Azurill.png []
/wiki/File:0299Nosepass.png []
/wiki/File:0300Skitty.png []
/wiki/File:0301Delcatty.png []
/wiki/File:0302Sableye.png ['/wiki/File:0302Sableye-Mega.png']
/wiki/File:0303Mawile.png ['/wiki/File:0303Mawile-Mega.png']
/wiki/File:0304Aron.png []
/wiki/File:0305Lairon.png []
/wiki/File:0306Aggron.png ['/wiki/File:0306Aggron-Mega.png']
/wiki/File:0307Meditite.png []
/wiki/File:0308Medicham.png ['/wiki/File:0308Medicham-Mega.png']
Bearbeitet: 350/1195
/wiki/File:0309Electrike.png []
/wiki/File:0310Manectric.png ['/wiki/File:0310Manectric-Mega.png']
/wiki/File:0311Plusle.png []
/wiki/File:0312Minun.png []
/wiki/File:0313Volbeat.png []
/wiki/File:0314Illumise.png []
/wiki/File:0315Roselia.png []
/wiki/File:0316Gulpin.png []
/wiki/File:0317Swalot.png []
/wiki/File:0318Carvanha.png []
/wiki/File:0319Sharpedo.png ['/wiki/File:0319Sharpedo-Mega.png']
/wiki/File:0320Wailmer.png []
/wiki/File:0321Wailord.png []
/wiki/File:0322Numel.png []
/wiki/File:0323Camerupt.png ['/wiki/File:0323Camerupt-Mega.png']
/wiki/File:0324Torkoal.png []
/wiki/File:0325Spoink.png []
/wiki/File:0326Grumpig.png []
/wiki/File:0327Spinda.png []
/wiki/File:0328Trapinch.png []
/wiki/File:0329Vibrava.png []
/wiki/File:0330Flygon.png []
/wiki/File:0331Cacnea.png []
/wiki/File:0332Cacturne.png []
/wiki/File:0333Swablu.png []
/wiki/File:0334Altaria.png ['/wiki/File:0334Altaria-Mega.png']
/wiki/File:0335Zangoose.png []
/wiki/File:0336Seviper.png []
/wiki/File:0337Lunatone.png []
/wiki/File:0338Solrock.png []
/wiki/File:0339Barboach.png []
/wiki/File:0340Whiscash.png []
/wiki/File:0341Corphish.png []
/wiki/File:0342Crawdaunt.png []
/wiki/File:0343Baltoy.png []
/wiki/File:0344Claydol.png []
/wiki/File:0345Lileep.png []
/wiki/File:0346Cradily.png []
/wiki/File:0347Anorith.png []
/wiki/File:0348Armaldo.png []
/wiki/File:0349Feebas.png []
/wiki/File:0350Milotic.png []
/wiki/File:0351Castform.png ['/wiki/File:0351Castform-Sunny.png', '/wiki/File:0351Castform-Rainy.png', '/wiki/File:0351Castform-Snowy.png']
/wiki/File:0352Kecleon.png []
/wiki/File:0353Shuppet.png []
/wiki/File:0354Banette.png ['/wiki/File:0354Banette-Mega.png']
/wiki/File:0355Duskull.png []
/wiki/File:0356Dusclops.png []
/wiki/File:0357Tropius.png []
/wiki/File:0358Chimecho.png ['/wiki/File:0358Chimecho-Mega.png']
Bearbeitet: 400/1195
/wiki/File:0359Absol.png ['/wiki/File:0359Absol-Mega.png', '/wiki/File:0359Absol-Mega_Z.png']
/wiki/File:0360Wynaut.png []
/wiki/File:0361Snorunt.png []
/wiki/File:0362Glalie.png ['/wiki/File:0362Glalie-Mega.png']
/wiki/File:0363Spheal.png []
/wiki/File:0364Sealeo.png []
/wiki/File:0365Walrein.png []
/wiki/File:0366Clamperl.png []
/wiki/File:0367Huntail.png []
/wiki/File:0368Gorebyss.png []
/wiki/File:0369Relicanth.png []
/wiki/File:0370Luvdisc.png []
/wiki/File:0371Bagon.png []
/wiki/File:0372Shelgon.png []
/wiki/File:0373Salamence.png ['/wiki/File:0373Salamence-Mega.png']
/wiki/File:0374Beldum.png []
/wiki/File:0375Metang.png []
/wiki/File:0376Metagross.png ['/wiki/File:0376Metagross-Mega.png']
/wiki/File:0377Regirock.png []
/wiki/File:0378Regice.png []
/wiki/File:0379Registeel.png []
/wiki/File:0380Latias.png ['/wiki/File:0380Latias-Mega.png']
/wiki/File:0381Latios.png ['/wiki/File:0381Latios-Mega.png']
/wiki/File:0382Kyogre.png ['/wiki/File:0382Kyogre-Primal.png']
/wiki/File:0383Groudon.png ['/wiki/File:0383Groudon-Primal.png']
/wiki/File:0384Rayquaza.png ['/wiki/File:0384Rayquaza-Mega.png']
/wiki/File:0385Jirachi.png []
/wiki/File:0386Deoxys.png ['/wiki/File:0386Deoxys-Attack.png', '/wiki/File:0386Deoxys-Defense.png', '/wiki/File:0386Deoxys-Speed.png']
/wiki/File:PlatinumTitle.png []
/wiki/File:0387Turtwig.png []
/wiki/File:0388Grotle.png []
/wiki/File:0389Torterra.png []
/wiki/File:0390Chimchar.png []
/wiki/File:0391Monferno.png []
/wiki/File:0392Infernape.png []
/wiki/File:0393Piplup.png []
/wiki/File:0394Prinplup.png []
/wiki/File:0395Empoleon.png []
/wiki/File:0396Starly.png []
/wiki/File:0397Staravia.png []
/wiki/File:0398Staraptor.png ['/wiki/File:0398Staraptor-Mega.png']
/wiki/File:0399Bidoof.png []
/wiki/File:0400Bibarel.png []
/wiki/File:0401Kricketot.png []
/wiki/File:0402Kricketune.png []
/wiki/File:0403Shinx.png []
/wiki/File:0404Luxio.png []
/wiki/File:0405Luxray.png []
/wiki/File:0406Budew.png []
/wiki/File:0407Roserade.png []
Bearbeitet: 450/1195
/wiki/File:0408Cranidos.png []
/wiki/File:0409Rampardos.png []
/wiki/File:0410Shieldon.png []
/wiki/File:0411Bastiodon.png []
/wiki/File:0412Burmy-Plant.png ['/wiki/File:0412Burmy-Sandy.png', '/wiki/File:0412Burmy-Trash.png']
/wiki/File:0413Wormadam-Plant.png ['/wiki/File:0413Wormadam-Sandy.png', '/wiki/File:0413Wormadam-Trash.png']
/wiki/File:0414Mothim.png []
/wiki/File:0415Combee.png []
/wiki/File:0416Vespiquen.png []
/wiki/File:0417Pachirisu.png []
/wiki/File:0418Buizel.png []
/wiki/File:0419Floatzel.png []
/wiki/File:0420Cherubi.png []
/wiki/File:0421Cherrim.png ['/wiki/File:0421Cherrim-Sunshine.png']
/wiki/File:0422Shellos-West.png ['/wiki/File:0422Shellos-East.png']
/wiki/File:0423Gastrodon-West.png ['/wiki/File:0423Gastrodon-East.png']
/wiki/File:0424Ambipom.png []
/wiki/File:0425Drifloon.png []
/wiki/File:0426Drifblim.png []
/wiki/File:0427Buneary.png []
/wiki/File:0428Lopunny.png ['/wiki/File:0428Lopunny-Mega.png']
/wiki/File:0429Mismagius.png []
/wiki/File:0430Honchkrow.png []
/wiki/File:0431Glameow.png []
/wiki/File:0432Purugly.png []
/wiki/File:0433Chingling.png []
/wiki/File:0434Stunky.png []
/wiki/File:0435Skuntank.png []
/wiki/File:0436Bronzor.png []
/wiki/File:0437Bronzong.png []
/wiki/File:0438Bonsly.png []
/wiki/File:0439Mime_Jr.png []
/wiki/File:0440Happiny.png []
/wiki/File:0441Chatot.png []
/wiki/File:0442Spiritomb.png []
/wiki/File:0443Gible.png []
/wiki/File:0444Gabite.png []
/wiki/File:0445Garchomp.png ['/wiki/File:0445Garchomp-Mega.png', '/wiki/File:0445Garchomp-Mega_Z.png']
/wiki/File:0446Munchlax.png []
/wiki/File:0447Riolu.png []
/wiki/File:0448Lucario.png ['/wiki/File:0448Lucario-Mega.png', '/wiki/File:0448Lucario-Mega_Z.png']
/wiki/File:0449Hippopotas.png []
/wiki/File:0450Hippowdon.png []
/wiki/File:0451Skorupi.png []
/wiki/File:0452Drapion.png []
/wiki/File:0453Croagunk.png []
/wiki/File:0454Toxicroak.png []
/wiki/File:0455Carnivine.png []
/wiki/File:0456Finneon.png []
/wiki/File:0457Lumineon.png []
Bearbeitet: 500/1195
/wiki/File:0458Mantyke.png []
/wiki/File:0459Snover.png []
/wiki/File:0460Abomasnow.png ['/wiki/File:0460Abomasnow-Mega.png']
/wiki/File:0461Weavile.png []
/wiki/File:0462Magnezone.png []
/wiki/File:0463Lickilicky.png []
/wiki/File:0464Rhyperior.png []
/wiki/File:0465Tangrowth.png []
/wiki/File:0466Electivire.png []
/wiki/File:0467Magmortar.png []
/wiki/File:0468Togekiss.png []
/wiki/File:0469Yanmega.png []
/wiki/File:0470Leafeon.png []
/wiki/File:0471Glaceon.png []
/wiki/File:0472Gliscor.png []
/wiki/File:0473Mamoswine.png []
/wiki/File:0474Porygon-Z.png []
/wiki/File:0475Gallade.png ['/wiki/File:0475Gallade-Mega.png']
/wiki/File:0476Probopass.png []
/wiki/File:0477Dusknoir.png []
/wiki/File:0478Froslass.png ['/wiki/File:0478Froslass-Mega.png']

,wiki_path,wiki_url,main_thumbnail,main_thumbnail_url,relevant_other_thumbnails,relevant_other_thumbnail_urls,all_other_thumbnails
0,/wiki/Kanto,https://bulbapedia.bulbagarden.net/wiki/Kanto,/wiki/File:PE_Kanto_Map.png,https://bulbapedia.bulbagarden.net/wiki/File:P...,[],[],[]
1,/wiki/Johto,https://bulbapedia.bulbagarden.net/wiki/Johto,/wiki/File:JohtoMap.png,https://bulbapedia.bulbagarden.net/wiki/File:J...,[],[],[]
2,/wiki/Hoenn,https://bulbapedia.bulbagarden.net/wiki/Hoenn,/wiki/File:Hoenn_ORAS.png,https://bulbapedia.bulbagarden.net/wiki/File:H...,[],[],[]
3,/wiki/Sinnoh,https://bulbapedia.bulbagarden.net/wiki/Sinnoh,/wiki/File:Sinnoh_BDSP_artwork.png,https://bulbapedia.bulbagarden.net/wiki/File:S...,[],[],[]
4,/wiki/Unova,https://bulbapedia.bulbagarden.net/wiki/Unova,/wiki/File:Unova_B2W2_alt.png,https://bulbapedia.bulbagarden.net/wiki/File:U...,[],[],[]
5,/wiki/Kalos,https://bulbapedia.bulbagarden.net/wiki/Kalos,/wiki/File:Kalos_alt.png,https://bulbapedia.bulbagarden.net/wiki/File:K...,[],[],[]
6,/wiki/Alola,https://bulbapedia.bulbagarden.net/wiki/Alola,/wiki/File:Alola_USUM_artwork.png,https://bulbapedia.bulbagarden.net/wiki/File:A...,[],[],[]
7,/wiki/Galar,https://bulbapedia.bulbagarden.net/wiki/Galar,/wiki/File:Galar_artwork.png,https://bulbapedia.bulbagarden.net/wiki/File:G...,[],[],[]
8,/wiki/Hisui,https://bulbapedia.bulbagarden.net/wiki/Hisui,/wiki/File:Legends_Arceus_Hisui.png,https://bulbapedia.bulbagarden.net/wiki/File:L...,[],[],[]
9,/wiki/Paldea,https://bulbapedia.bulbagarden.net/wiki/Paldea,/wiki/File:Paldea_artwork.png,https://bulbapedia.bulbagarden.net/wiki/File:P...,[],[],[]
10,/wiki/Victini_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Victin...,/wiki/File:0494Victini.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body12.png, /wiki/File:F0494.png, ..."
11,/wiki/Generation_II,https://bulbapedia.bulbagarden.net/wiki/Genera...,/wiki/File:SilverTitle.png,https://bulbapedia.bulbagarden.net/wiki/File:S...,[],[],[]
12,/wiki/Generation_I,https://bulbapedia.bulbagarden.net/wiki/Genera...,/wiki/File:GreenTitle.png,https://bulbapedia.bulbagarden.net/wiki/File:G...,[],[],[]
13,/wiki/Bulbasaur_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Bulbas...,/wiki/File:0001Bulbasaur.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body08.png, /wiki/File:F0001.png, ..."
14,/wiki/Ivysaur_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Ivysau...,/wiki/File:0002Ivysaur.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body08.png, /wiki/File:F0002.png, ..."
15,/wiki/Venusaur_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Venusa...,/wiki/File:0003Venusaur.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,"[/wiki/File:0003Venusaur-Mega.png, /wiki/File:...",[https://bulbapedia.bulbagarden.net/wiki/File:...,"[/wiki/File:0003Venusaur-Mega.png, /wiki/File:..."
16,/wiki/Charmander_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Charma...,/wiki/File:0004Charmander.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body06.png, /wiki/File:F0004.png, ..."
17,/wiki/Charmeleon_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Charme...,/wiki/File:0005Charmeleon.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body06.png, /wiki/File:F0005.png, ..."
18,/wiki/Charizard_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Chariz...,/wiki/File:0006Charizard.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,"[/wiki/File:0006Charizard-Mega_X.png, /wiki/Fi...",[https://bulbapedia.bulbagarden.net/wiki/File:...,"[/wiki/File:0006Charizard-Mega_X.png, /wiki/Fi..."
19,/wiki/Squirtle_(Pok%C3%A9mon),https://bulbapedia.bulbagarden.net/wiki/Squirt...,/wiki/File:0007Squirtle.png,https://bulbapedia.bulbagarden.net/wiki/File:0...,[],[],"[/wiki/File:Body06.png, /wiki/File:F0007.png, ..."

In [10]:
import json
from pathlib import Path
from urllib.parse import unquote
import re
import pandas as pd

def parse_pokemon_filename(filename: str) -> dict:
    """
    Extrahiert aus Dateinamen oder Wiki-Links wie:
    - 0569Garbodor-Gigantamax.png
    - /wiki/File:0009Blastoise-Mega.png
    generisch: index, name, zusatz.
    """
    text = str(filename).strip()

    # URL-encoding aufloesen (%20 etc.)
    text = unquote(text)

    # Wiki-Praefix entfernen, falls vorhanden
    if text.startswith("/wiki/File:"):
        text = text[len("/wiki/File:"):]
    elif text.startswith("File:"):
        text = text[len("File:"):]

    # Nur Dateiname ohne Pfad, Query, Fragment
    base = Path(text.split("?", 1)[0].split("#", 1)[0]).name
    stem = base.rsplit(".", 1)[0] if "." in base else base

    # Fuehrende Nummer extrahieren
    match = re.match(r"^(?P<index>\d+)(?P<rest>.+)$", stem)
    if not match:
        return {"index": "", "name": stem, "zusatz": ""}

    index = match.group("index")
    rest = match.group("rest")

    # Ersten Suffix-Teil als Zusatz behandeln
    parts = re.split(r"[-_]", rest, maxsplit=1)
    name = parts[0]
    zusatz = parts[1] if len(parts) > 1 else ""

    return {"index": index, "name": name, "zusatz": zusatz}

def _normalize_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip().lower()

def _normalize_nr(value):
    if pd.isna(value):
        return ""
    try:
        return f"{int(value):04d}"
    except Exception:
        s = str(value).strip()
        return s.zfill(4) if s.isdigit() else s

def find_matching_df_edited_indices(df_edited: pd.DataFrame, more: dict) -> list:
    """Match über index (nr) oder name (name_en/name_de)."""
    matched = set()

    target_index = str(more.get("index", "")).strip()
    target_name = _normalize_text(more.get("name", ""))

    if target_index:
        nr_norm = df_edited["nr"].apply(_normalize_nr) if "nr" in df_edited.columns else pd.Series([], dtype=str)
        idx_hits = df_edited.index[nr_norm == target_index].tolist()
        matched.update(idx_hits)

    if target_name:
        for col in ["name_en", "name_de"]:
            if col in df_edited.columns:
                col_norm = df_edited[col].apply(_normalize_text)
                name_hits = df_edited.index[col_norm == target_name].tolist()
                matched.update(name_hits)

    return sorted(matched)

json_path = "../data/pokemon/pokedex_edited.json"
df_edited = pd.read_json(json_path, orient="records")

# if "weitere_erscheinungsformen" not in df_edited.columns:
#     df_edited["weitere_erscheinungsformen"] = None

updates = 0
no_match = []

for _, row in forms_df.iterrows():
    thumbs = row.get("relevant_other_thumbnails", [])
    if not isinstance(thumbs, list):
        continue

    for thumb in thumbs:
        more = parse_pokemon_filename(thumb)

        # Nur Einträge mit erkanntem Index übernehmen
        if not str(more.get("index", "")).strip():
            continue

        target_indices = find_matching_df_edited_indices(df_edited, more)
        if not target_indices:
            no_match.append({"thumb": thumb, "parsed": more})
            continue

        payload = {
            "form_name": more.get("zusatz", ""),
            "link_bulbpedia": thumb,
        }

        for i in target_indices:
            existing = df_edited.at[i, "weitere_erscheinungsformen"]

            if not isinstance(existing, list):
                existing = []

            # Duplikat über link_bulbpedia vermeiden
            exists = any(
                isinstance(x, dict) and x.get("link_bulbpedia") == payload["link_bulbpedia"]
                for x in existing
            )
            if not exists:
                existing.append(payload)
                df_edited.at[i, "weitere_erscheinungsformen"] = existing
                updates += 1

print(f"Hinzugefügte Formen-Einträge: {updates}")
print(f"Ohne Match in df_edited: {len(no_match)}")

# Vorschau auf Zeilen mit mindestens einer weiteren Erscheinungsform
# preview = df_edited[df_edited["weitere_erscheinungsformen"].apply(lambda x: isinstance(x, list) and len(x) > 0)]
# preview[["nr", "name_en", "name_de", "weitere_erscheinungsformen"]].head(20)
# preview.head(20)
# print(json.dumps(preview[["nr", "name_en", "name_de", "weitere_erscheinungsformen"]].head(20).to_dict(orient="records"), indent=2, ensure_ascii=False))

df_edited.to_json("../data/pokemon/pokedex_extended.json", orient="records", force_ascii=False, indent=2)

Hinzugefügte Formen-Einträge: 274
Ohne Match in df_edited: 0

In [39]:
# Alle link_bulbpedia aus df_edited -> weitere_erscheinungsformen ausgeben
for _, row in df_edited[0:10].iterrows():
    forms = row.get("weitere_erscheinungsformen")

    if not isinstance(forms, list):
        continue

    
    print(forms)


    for form in forms:
        if not isinstance(form, dict):
            continue

        link = form.get("link_bulbpedia")
        if isinstance(link, str) and link.strip():
            print(link)

[{'norm_name': 'Mega', 'link_bulbpedia': '/wiki/File:0003Venusaur-Mega.png'}, {'norm_name': 'Gigantamax', 'link_bulbpedia': '/wiki/File:0003Venusaur-Gigantamax.png'}]
/wiki/File:0003Venusaur-Mega.png
/wiki/File:0003Venusaur-Gigantamax.png
[{'norm_name': 'Mega_X', 'link_bulbpedia': '/wiki/File:0006Charizard-Mega_X.png'}, {'norm_name': 'Mega_Y', 'link_bulbpedia': '/wiki/File:0006Charizard-Mega_Y.png'}, {'norm_name': 'Gigantamax', 'link_bulbpedia': '/wiki/File:0006Charizard-Gigantamax.png'}]
/wiki/File:0006Charizard-Mega_X.png
/wiki/File:0006Charizard-Mega_Y.png
/wiki/File:0006Charizard-Gigantamax.png

In [12]:
import re
import requests
from urllib.parse import urljoin
from pathlib import Path

BASE_BULBA = "https://bulbapedia.bulbagarden.net"


def extract_original_download_link(file_page_html: str, page_url: str) -> str:
    # 1) Häufigster Fall auf MediaWiki-File-Seiten
    m = re.search(
        r'<div[^>]*class=["\\"][^"\\"]*fullImageLink[^"\\"]*["\\"][^>]*>\s*<a[^>]*href=["\\"]([^"\\"]+)["\\"]',
        file_page_html,
        flags=re.IGNORECASE,
    )
    if m:
        return urljoin(page_url, m.group(1))

    # 2) Fallback: Linktext 'Original file' / 'Original-Datei'
    m = re.search(
        r'<a[^>]*href=["\\"]([^"\\"]+)["\\"][^>]*>\s*(?:Original file|Original-Datei)\s*</a>',
        file_page_html,
        flags=re.IGNORECASE,
    )
    if m:
        return urljoin(page_url, m.group(1))

    # 3) Fallback: erster direkter Upload-Link
    m = re.search(r'href=["\\"](https?://[^"\\"]*/upload/[^"\\"]+)["\\"]', file_page_html, flags=re.IGNORECASE)
    if m:
        return m.group(1)

    return ""


sess = requests.Session()
sess.headers.update({"User-Agent": "Mozilla/5.0 (compatible; bulba-original-link-extractor/1.0)"})

updated = 0
missing = 0
errors = 0
seen = set()

for row_idx, row in df_edited.iterrows():
    forms = row.get("weitere_erscheinungsformen")
    if not isinstance(forms, list):
        continue

    for form in forms:
        if not isinstance(form, dict):
            continue

        link = form.get("link_bulbpedia")
        if not isinstance(link, str) or not link.strip():
            continue

        link = link.strip()
        file_page_url = urljoin(BASE_BULBA, link)

        # Optionales Request-Deduping pro Datei-Link
        if link in seen and form.get("sprite_bulbapedia"):
            continue

        try:
            r = sess.get(file_page_url, timeout=20)
            r.raise_for_status()
            original_url = extract_original_download_link(r.text, file_page_url)
        except Exception as e:
            errors += 1
            print(f"Fehler bei {file_page_url}: {e}")
            continue

        seen.add(link)

        if original_url:
            # Direkt im passenden Eintrag setzen
            form["sprite_bulbapedia"] = original_url
            updated += 1
            print(f"Gesetzt: {row.get('name_de', row.get('name_en', row_idx))} -> {original_url}")
        else:
            missing += 1
            print(f"Kein Original-Link gefunden: {file_page_url}")

print(f"Aktualisiert: {updated}, Kein Link gefunden: {missing}, Fehler: {errors}")

# Ergebnis persistieren
json_out = Path("../data/pokemon/pokedex_extended_right_link.json")
df_edited.to_json(json_out, orient="records", force_ascii=False, indent=2)
print(f"Gespeichert: {json_out.resolve()}")

Gesetzt: Bisaflor -> https://archives.bulbagarden.net/media/upload/f/f7/0003Venusaur-Mega.png
Gesetzt: Bisaflor -> https://archives.bulbagarden.net/media/upload/4/45/0003Venusaur-Gigantamax.png
Gesetzt: Glurak -> https://archives.bulbagarden.net/media/upload/3/35/0006Charizard-Mega_X.png
Gesetzt: Glurak -> https://archives.bulbagarden.net/media/upload/a/a0/0006Charizard-Mega_Y.png
Gesetzt: Glurak -> https://archives.bulbagarden.net/media/upload/0/0c/0006Charizard-Gigantamax.png
Gesetzt: Turtok -> https://archives.bulbagarden.net/media/upload/6/6e/0009Blastoise-Mega.png
Gesetzt: Turtok -> https://archives.bulbagarden.net/media/upload/b/bd/0009Blastoise-Gigantamax.png
Gesetzt: Smettbo -> https://archives.bulbagarden.net/media/upload/e/ee/0012Butterfree-Gigantamax.png
Gesetzt: Bibor -> https://archives.bulbagarden.net/media/upload/7/73/0015Beedrill-Mega.png
Gesetzt: Tauboss -> https://archives.bulbagarden.net/media/upload/f/f6/0018Pidgeot-Mega.png
Gesetzt: Rattfratz -> https://archives.bulbagarden.net/media/upload/b/be/0019Rattata-Alola.png
Gesetzt: Rattikarl -> https://archives.bulbagarden.net/media/upload/a/ad/0020Raticate-Alola.png
Gesetzt: Pikachu -> https://archives.bulbagarden.net/media/upload/b/b4/0025Pikachu-Cosplay.png
Gesetzt: Pikachu -> https://archives.bulbagarden.net/media/upload/c/c0/0025Pikachu-Partner_Cap.png
Gesetzt: Pikachu -> https://archives.bulbagarden.net/media/upload/8/8c/0025Pikachu-Gigantamax.png
Gesetzt: Raichu -> https://archives.bulbagarden.net/media/upload/6/65/0026Raichu-Alola.png
Gesetzt: Raichu -> https://archives.bulbagarden.net/media/upload/9/9f/0026Raichu-Mega_X.png
Gesetzt: Raichu -> https://archives.bulbagarden.net/media/upload/6/65/0026Raichu-Mega_Y.png
Gesetzt: Sandan -> https://archives.bulbagarden.net/media/upload/f/f4/0027Sandshrew-Alola.png
Gesetzt: Sandamer -> https://archives.bulbagarden.net/media/upload/e/e0/0028Sandslash-Alola.png
Gesetzt: Pixi -> https://archives.bulbagarden.net/media/upload/5/5a/0036Clefable-Mega.png
Gesetzt: Vulpix -> https://archives.bulbagarden.net/media/upload/6/6b/0037Vulpix-Alola.png
Gesetzt: Vulnona -> https://archives.bulbagarden.net/media/upload/7/7f/0038Ninetales-Alola.png
Gesetzt: Digda -> https://archives.bulbagarden.net/media/upload/6/61/0050Diglett-Alola.png
Gesetzt: Digdri -> https://archives.bulbagarden.net/media/upload/9/91/0051Dugtrio-Alola.png
Gesetzt: Mauzi -> https://archives.bulbagarden.net/media/upload/3/32/0052Meowth-Alola.png
Gesetzt: Mauzi -> https://archives.bulbagarden.net/media/upload/3/3d/0052Meowth-Galar.png
Gesetzt: Mauzi -> https://archives.bulbagarden.net/media/upload/0/08/0052Meowth-Gigantamax.png
Gesetzt: Snobilikat -> https://archives.bulbagarden.net/media/upload/8/8c/0053Persian-Alola.png
Gesetzt: Fukano -> https://archives.bulbagarden.net/media/upload/3/3b/0058Growlithe-Hisui.png
Gesetzt: Arkani -> https://archives.bulbagarden.net/media/upload/7/79/0059Arcanine-Hisui.png
Gesetzt: Simsala -> https://archives.bulbagarden.net/media/upload/a/ac/0065Alakazam-Mega.png
Gesetzt: Machomei -> https://archives.bulbagarden.net/media/upload/e/e4/0068Machamp-Gigantamax.png
Gesetzt: Sarzenia -> https://archives.bulbagarden.net/media/upload/0/06/0071Victreebel-Mega.png
Gesetzt: Kleinstein -> https://archives.bulbagarden.net/media/upload/a/a4/0074Geodude-Alola.png
Gesetzt: Georok -> https://archives.bulbagarden.net/media/upload/0/05/0075Graveler-Alola.png
Gesetzt: Geowaz -> https://archives.bulbagarden.net/media/upload/9/9e/0076Golem-Alola.png
Gesetzt: Ponita -> https://archives.bulbagarden.net/media/upload/9/93/0077Ponyta-Galar.png
Gesetzt: Gallopa -> https://archives.bulbagarden.net/media/upload/f/f2/0078Rapidash-Galar.png
Gesetzt: Flegmon -> https://archives.bulbagarden.net/media/upload/e/e5/0079Slowpoke-Galar.png
Gesetzt: Lahmus -> https://archives.bulbagarden.net/media/upload/b/b3/0080Slowbro-Galar.png
Gesetzt: Lahmus -> https://archives.bulbagarden.net/media/upload/0/0d/0080Slowbro-Mega.png
Gesetzt: Porenta -> https://archives.bulbagarden.net/media/upload/d/d1/0083Farfetch%27d-Galar.png
Gesetzt: Sleima -> https://archives.bulbagarden.net/media/upload/2/24/0088Grimer-Alola.png
Gesetzt: Sleimok -> https://archives.bulbagarden.net/media/upload/8/8c/0089Muk-Alola.png
Gesetzt: Gengar -> https://archives.bulbagarden.net/media/upload/c/c8/0094Gengar-Mega.png
Gesetzt: Gengar -> https://archives.bulbagarden.net/media/upload/4/4a/0094Gengar-Gigantamax.png
Gesetzt: Kingler -> https://archives.bulbagarden.net/media/upload/2/2d/0099Kingler-Gigantamax.png
Gesetzt: Voltobal -> https://archives.bulbagarden.net/media/upload/f/fc/0100Voltorb-Hisui.png
Gesetzt: Lektrobal -> https://archives.bulbagarden.net/media/upload/b/be/0101Electrode-Hisui.png
Gesetzt: Kokowei -> https://archives.bulbagarden.net/media/upload/9/94/0103Exeggutor-Alola.png
Gesetzt: Knogga -> https://archives.bulbagarden.net/media/upload/f/f2/0105Marowak-Alola.png
Gesetzt: Smogmog -> https://archives.bulbagarden.net/media/upload/3/32/0110Weezing-Galar.png
Gesetzt: Kangama -> https://archives.bulbagarden.net/media/upload/2/2f/0115Kangaskhan-Mega.png
Gesetzt: Starmie -> https://archives.bulbagarden.net/media/upload/2/2c/0121Starmie-Mega.png
Gesetzt: Pantimos -> https://archives.bulbagarden.net/media/upload/7/7c/0122Mr._Mime-Galar.png
Gesetzt: Pinsir -> https://archives.bulbagarden.net/media/upload/1/1d/0127Pinsir-Mega.png
Gesetzt: Tauros -> https://archives.bulbagarden.net/media/upload/2/25/0128Tauros-Paldea_Combat.png
Gesetzt: Tauros -> https://archives.bulbagarden.net/media/upload/f/f5/0128Tauros-Paldea_Blaze.png
Gesetzt: Tauros -> https://archives.bulbagarden.net/media/upload/d/d9/0128Tauros-Paldea_Aqua.png
Gesetzt: Garados -> https://archives.bulbagarden.net/media/upload/c/cd/0130Gyarados-Mega.png
Gesetzt: Lapras -> https://archives.bulbagarden.net/media/upload/b/b6/0131Lapras-Gigantamax.png
Gesetzt: Evoli -> https://archives.bulbagarden.net/media/upload/e/e2/0133Eevee-Gigantamax.png
Gesetzt: Aerodactyl -> https://archives.bulbagarden.net/media/upload/1/18/0142Aerodactyl-Mega.png
Gesetzt: Relaxo -> https://archives.bulbagarden.net/media/upload/d/d0/0143Snorlax-Gigantamax.png
Gesetzt: Arktos -> https://archives.bulbagarden.net/media/upload/5/5a/0144Articuno-Galar.png
Gesetzt: Zapdos -> https://archives.bulbagarden.net/media/upload/7/75/0145Zapdos-Galar.png
Gesetzt: Lavados -> https://archives.bulbagarden.net/media/upload/e/e4/0146Moltres-Galar.png
Gesetzt: Dragoran -> https://archives.bulbagarden.net/media/upload/3/3e/0149Dragonite-Mega.png
Gesetzt: Mewtu -> https://archives.bulbagarden.net/media/upload/f/f8/0150Mewtwo-Mega_X.png
Gesetzt: Mewtu -> https://archives.bulbagarden.net/media/upload/3/30/0150Mewtwo-Mega_Y.png
Gesetzt: Meganie -> https://archives.bulbagarden.net/media/upload/e/e1/0154Meganium-Mega.png
Gesetzt: Tornupto -> https://archives.bulbagarden.net/media/upload/7/7c/0157Typhlosion-Hisui.png
Gesetzt: Impergator -> https://archives.bulbagarden.net/media/upload/4/42/0160Feraligatr-Mega.png
Gesetzt: Ampharos -> https://archives.bulbagarden.net/media/upload/c/c4/0181Ampharos-Mega.png
Gesetzt: Felino -> https://archives.bulbagarden.net/media/upload/b/bb/0194Wooper-Paldea.png
Gesetzt: Laschoking -> https://archives.bulbagarden.net/media/upload/0/06/0199Slowking-Galar.png
Gesetzt: Stahlos -> https://archives.bulbagarden.net/media/upload/8/80/0208Steelix-Mega.png
Gesetzt: Baldorfish -> https://archives.bulbagarden.net/media/upload/a/a5/0211Qwilfish-Hisui.png
Gesetzt: Scherox -> https://archives.bulbagarden.net/media/upload/9/98/0212Scizor-Mega.png
Gesetzt: Skaraborn -> https://archives.bulbagarden.net/media/upload/8/83/0214Heracross-Mega.png
Gesetzt: Sniebel -> https://archives.bulbagarden.net/media/upload/9/90/0215Sneasel-Hisui.png
Gesetzt: Corasonn -> https://archives.bulbagarden.net/media/upload/b/bf/0222Corsola-Galar.png
Gesetzt: Panzaeron -> https://archives.bulbagarden.net/media/upload/4/4e/0227Skarmory-Mega.png
Gesetzt: Hundemon -> https://archives.bulbagarden.net/media/upload/9/95/0229Houndoom-Mega.png
Gesetzt: Despotar -> https://archives.bulbagarden.net/media/upload/d/dc/0248Tyranitar-Mega.png
Gesetzt: Gewaldro -> https://archives.bulbagarden.net/media/upload/f/f5/0254Sceptile-Mega.png
Gesetzt: Lohgock -> https://archives.bulbagarden.net/media/upload/8/85/0257Blaziken-Mega.png
Gesetzt: Sumpex -> https://archives.bulbagarden.net/media/upload/b/b6/0260Swampert-Mega.png
Gesetzt: Zigzachs -> https://archives.bulbagarden.net/media/upload/0/00/0263Zigzagoon-Galar.png
Gesetzt: Geradaks -> https://archives.bulbagarden.net/media/upload/3/37/0264Linoone-Galar.png
Gesetzt: Guardevoir -> https://archives.bulbagarden.net/media/upload/3/3d/0282Gardevoir-Mega.png
Gesetzt: Zobiris -> https://archives.bulbagarden.net/media/upload/c/c9/0302Sableye-Mega.png
Gesetzt: Flunkifer -> https://archives.bulbagarden.net/media/upload/e/e6/0303Mawile-Mega.png
Gesetzt: Stolloss -> https://archives.bulbagarden.net/media/upload/2/21/0306Aggron-Mega.png
Gesetzt: Meditalis -> https://archives.bulbagarden.net/media/upload/5/52/0308Medicham-Mega.png
Gesetzt: Voltenso -> https://archives.bulbagarden.net/media/upload/4/48/0310Manectric-Mega.png
Gesetzt: Tohaido -> https://archives.bulbagarden.net/media/upload/e/e5/0319Sharpedo-Mega.png
Gesetzt: Camerupt -> https://archives.bulbagarden.net/media/upload/7/7b/0323Camerupt-Mega.png
Gesetzt: Altaria -> https://archives.bulbagarden.net/media/upload/d/dc/0334Altaria-Mega.png
Gesetzt: Formeo -> https://archives.bulbagarden.net/media/upload/9/90/0351Castform-Sunny.png
Gesetzt: Formeo -> https://archives.bulbagarden.net/media/upload/a/ab/0351Castform-Rainy.png
Gesetzt: Formeo -> https://archives.bulbagarden.net/media/upload/3/34/0351Castform-Snowy.png
Gesetzt: Banette -> https://archives.bulbagarden.net/media/upload/5/5f/0354Banette-Mega.png
Gesetzt: Palimpalim -> https://archives.bulbagarden.net/media/upload/b/b6/0358Chimecho-Mega.png
Gesetzt: Absol -> https://archives.bulbagarden.net/media/upload/d/d7/0359Absol-Mega.png
Gesetzt: Absol -> https://archives.bulbagarden.net/media/upload/e/e1/0359Absol-Mega_Z.png
Gesetzt: Firnontor -> https://archives.bulbagarden.net/media/upload/9/94/0362Glalie-Mega.png
Gesetzt: Brutalanda -> https://archives.bulbagarden.net/media/upload/2/26/0373Salamence-Mega.png
Gesetzt: Metagross -> https://archives.bulbagarden.net/media/upload/9/9d/0376Metagross-Mega.png
Gesetzt: Latias -> https://archives.bulbagarden.net/media/upload/5/5a/0380Latias-Mega.png
Gesetzt: Latios -> https://archives.bulbagarden.net/media/upload/c/c8/0381Latios-Mega.png
Gesetzt: Kyogre -> https://archives.bulbagarden.net/media/upload/9/9a/0382Kyogre-Primal.png
Gesetzt: Groudon -> https://archives.bulbagarden.net/media/upload/e/e5/0383Groudon-Primal.png
Gesetzt: Rayquaza -> https://archives.bulbagarden.net/media/upload/d/de/0384Rayquaza-Mega.png
Gesetzt: Deoxys -> https://archives.bulbagarden.net/media/upload/c/c6/0386Deoxys-Attack.png
Gesetzt: Deoxys -> https://archives.bulbagarden.net/media/upload/2/27/0386Deoxys-Defense.png
Gesetzt: Deoxys -> https://archives.bulbagarden.net/media/upload/1/17/0386Deoxys-Speed.png
Gesetzt: Staraptor -> https://archives.bulbagarden.net/media/upload/4/44/0398Staraptor-Mega.png
Gesetzt: Burmy -> https://archives.bulbagarden.net/media/upload/e/ee/0412Burmy-Sandy.png
Gesetzt: Burmy -> https://archives.bulbagarden.net/media/upload/4/42/0412Burmy-Trash.png
Gesetzt: Burmadame -> https://archives.bulbagarden.net/media/upload/b/b7/0413Wormadam-Sandy.png
Gesetzt: Burmadame -> https://archives.bulbagarden.net/media/upload/2/25/0413Wormadam-Trash.png
Gesetzt: Kinoso -> https://archives.bulbagarden.net/media/upload/9/90/0421Cherrim-Sunshine.png
Gesetzt: Schalellos -> https://archives.bulbagarden.net/media/upload/d/db/0422Shellos-East.png
Gesetzt: Gastrodon -> https://archives.bulbagarden.net/media/upload/5/57/0423Gastrodon-East.png
Gesetzt: Schlapor -> https://archives.bulbagarden.net/media/upload/c/c6/0428Lopunny-Mega.png
Gesetzt: Knakrack -> https://archives.bulbagarden.net/media/upload/6/66/0445Garchomp-Mega.png
Gesetzt: Knakrack -> https://archives.bulbagarden.net/media/upload/7/75/0445Garchomp-Mega_Z.png
Gesetzt: Lucario -> https://archives.bulbagarden.net/media/upload/c/cb/0448Lucario-Mega.png
Gesetzt: Lucario -> https://archives.bulbagarden.net/media/upload/5/56/0448Lucario-Mega_Z.png
Gesetzt: Rexblisar -> https://archives.bulbagarden.net/media/upload/3/33/0460Abomasnow-Mega.png
Gesetzt: Galagladi -> https://archives.bulbagarden.net/media/upload/5/5b/0475Gallade-Mega.png
Gesetzt: Frosdedje -> https://archives.bulbagarden.net/media/upload/6/65/0478Froslass-Mega.png
Gesetzt: Rotom -> https://archives.bulbagarden.net/media/upload/6/68/0479Rotom-Heat.png
Gesetzt: Rotom -> https://archives.bulbagarden.net/media/upload/3/36/0479Rotom-Wash.png
Gesetzt: Rotom -> https://archives.bulbagarden.net/media/upload/3/3f/0479Rotom-Frost.png
Gesetzt: Rotom -> https://archives.bulbagarden.net/media/upload/5/54/0479Rotom-Fan.png
Gesetzt: Rotom -> https://archives.bulbagarden.net/media/upload/6/6d/0479Rotom-Mow.png
Gesetzt: Dialga -> https://archives.bulbagarden.net/media/upload/9/92/0483Dialga-Origin.png
Gesetzt: Palkia -> https://archives.bulbagarden.net/media/upload/1/12/0484Palkia-Origin.png
Gesetzt: Heatran -> https://archives.bulbagarden.net/media/upload/c/c7/0485Heatran-Mega.png
Gesetzt: Giratina -> https://archives.bulbagarden.net/media/upload/6/61/0487Giratina-Origin.png
Gesetzt: Darkrai -> https://archives.bulbagarden.net/media/upload/9/96/0491Darkrai-Mega.png
Gesetzt: Shaymin -> https://archives.bulbagarden.net/media/upload/0/05/0492Shaymin-Sky.png
Gesetzt: Flambirex -> https://archives.bulbagarden.net/media/upload/c/c0/0500Emboar-Mega.png
Gesetzt: Admurai -> https://archives.bulbagarden.net/media/upload/2/2e/0503Samurott-Hisui.png
Gesetzt: Stalobor -> https://archives.bulbagarden.net/media/upload/d/d5/0530Excadrill-Mega.png
Gesetzt: Ohrdoch -> https://archives.bulbagarden.net/media/upload/d/d7/0531Audino-Mega.png
Gesetzt: Cerapendra -> https://archives.bulbagarden.net/media/upload/4/48/0545Scolipede-Mega.png
Gesetzt: Dressella -> https://archives.bulbagarden.net/media/upload/4/4c/0549Lilligant-Hisui.png
Gesetzt: Barschuft -> https://archives.bulbagarden.net/media/upload/2/27/0550Basculin-Blue.png
Gesetzt: Barschuft -> https://archives.bulbagarden.net/media/upload/3/34/0550Basculin-White.png
Gesetzt: Flampion -> https://archives.bulbagarden.net/media/upload/1/1c/0554Darumaka-Galar.png
Gesetzt: Flampivian -> https://archives.bulbagarden.net/media/upload/8/88/0555Darmanitan-Zen.png
Gesetzt: Flampivian -> https://archives.bulbagarden.net/media/upload/1/1a/0555Darmanitan-Galar.png
Gesetzt: Flampivian -> https://archives.bulbagarden.net/media/upload/9/97/0555Darmanitan-Galar_Zen.png
Gesetzt: Irokex -> https://archives.bulbagarden.net/media/upload/2/22/0560Scrafty-Mega.png
Gesetzt: Makabaja -> https://archives.bulbagarden.net/media/upload/0/05/0562Yamask-Galar.png
Gesetzt: Deponitox -> https://archives.bulbagarden.net/media/upload/0/04/0569Garbodor-Gigantamax.png
Gesetzt: Zorua -> https://archives.bulbagarden.net/media/upload/e/e9/0570Zorua-Hisui.png
Gesetzt: Zoroark -> https://archives.bulbagarden.net/media/upload/b/b2/0571Zoroark-Hisui.png
Gesetzt: Sesokitz -> https://archives.bulbagarden.net/media/upload/b/b5/0585Deerling-Summer.png
Gesetzt: Sesokitz -> https://archives.bulbagarden.net/media/upload/5/55/0585Deerling-Autumn.png
Gesetzt: Sesokitz -> https://archives.bulbagarden.net/media/upload/2/20/0585Deerling-Winter.png
Gesetzt: Kronjuwild -> https://archives.bulbagarden.net/media/upload/0/0f/0586Sawsbuck-Summer.png
Gesetzt: Kronjuwild -> https://archives.bulbagarden.net/media/upload/9/9f/0586Sawsbuck-Autumn.png
Gesetzt: Kronjuwild -> https://archives.bulbagarden.net/media/upload/7/79/0586Sawsbuck-Winter.png
Gesetzt: Zapplarang -> https://archives.bulbagarden.net/media/upload/6/61/0604Eelektross-Mega.png
Gesetzt: Skelabra -> https://archives.bulbagarden.net/media/upload/f/fd/0609Chandelure-Mega.png
Gesetzt: Flunschlik -> https://archives.bulbagarden.net/media/upload/4/40/0618Stunfisk-Galar.png
Gesetzt: Golgantes -> https://archives.bulbagarden.net/media/upload/8/87/0623Golurk-Mega.png
Gesetzt: Washakwil -> https://archives.bulbagarden.net/media/upload/e/e8/0628Braviary-Hisui.png
Gesetzt: Boreos -> https://archives.bulbagarden.net/media/upload/5/53/0641Tornadus-Therian.png
Gesetzt: Voltolos -> https://archives.bulbagarden.net/media/upload/3/3e/0642Thundurus-Therian.png
Gesetzt: Demeteros -> https://archives.bulbagarden.net/media/upload/4/44/0645Landorus-Therian.png
Gesetzt: Kyurem -> https://archives.bulbagarden.net/media/upload/5/5d/0646Kyurem-White.png
Gesetzt: Kyurem -> https://archives.bulbagarden.net/media/upload/e/e8/0646Kyurem-Black.png
Gesetzt: Keldeo -> https://archives.bulbagarden.net/media/upload/c/cf/0647Keldeo-Resolute.png
Gesetzt: Meloetta -> https://archives.bulbagarden.net/media/upload/f/f9/0648Meloetta-Pirouette.png
Gesetzt: Brigaron -> https://archives.bulbagarden.net/media/upload/d/d6/0652Chesnaught-Mega.png
Gesetzt: Fennexis -> https://archives.bulbagarden.net/media/upload/3/3a/0655Delphox-Mega.png
Gesetzt: Quajutsu -> https://archives.bulbagarden.net/media/upload/7/72/0658Greninja-Ash.png
Gesetzt: Quajutsu -> https://archives.bulbagarden.net/media/upload/e/e9/0658Greninja-Mega.png
Gesetzt: Pyroleo -> https://archives.bulbagarden.net/media/upload/5/5d/0668Pyroar-Mega.png
Gesetzt: Floette -> https://archives.bulbagarden.net/media/upload/a/a9/0670Floette-Eternal.png
Gesetzt: Floette -> https://archives.bulbagarden.net/media/upload/3/36/0670Floette-Mega.png
Gesetzt: Psiaugon -> https://archives.bulbagarden.net/media/upload/1/1f/0678Meowstic-Female.png
Gesetzt: Psiaugon -> https://archives.bulbagarden.net/media/upload/4/40/0678Meowstic-Mega.png
Gesetzt: Durengard -> https://archives.bulbagarden.net/media/upload/9/99/0681Aegislash-Blade.png
Gesetzt: Calamanero -> https://archives.bulbagarden.net/media/upload/a/ae/0687Malamar-Mega.png
Gesetzt: Thanathora -> https://archives.bulbagarden.net/media/upload/e/e9/0689Barbaracle-Mega.png
Gesetzt: Tandrak -> https://archives.bulbagarden.net/media/upload/9/97/0691Dragalge-Mega.png
Gesetzt: Resladero -> https://archives.bulbagarden.net/media/upload/4/49/0701Hawlucha-Mega.png
Gesetzt: Viscargot -> https://archives.bulbagarden.net/media/upload/4/4b/0705Sliggoo-Hisui.png
Gesetzt: Viscogon -> https://archives.bulbagarden.net/media/upload/b/b9/0706Goodra-Hisui.png
Gesetzt: Arktilas -> https://archives.bulbagarden.net/media/upload/e/ef/0713Avalugg-Hisui.png
Gesetzt: Zygarde -> https://archives.bulbagarden.net/media/upload/f/f8/0718Zygarde-10Percent.png
Gesetzt: Zygarde -> https://archives.bulbagarden.net/media/upload/f/fb/0718Zygarde-Complete.png
Gesetzt: Zygarde -> https://archives.bulbagarden.net/media/upload/8/8c/0718Zygarde-Mega.png
Gesetzt: Diancie -> https://archives.bulbagarden.net/media/upload/0/0c/0719Diancie-Mega.png
Gesetzt: Hoopa -> https://archives.bulbagarden.net/media/upload/a/a3/0720Hoopa-Unbound.png
Gesetzt: Silvarro -> https://archives.bulbagarden.net/media/upload/3/33/0724Decidueye-Hisui.png
Gesetzt: Krawell -> https://archives.bulbagarden.net/media/upload/7/75/0740Crabominable-Mega.png
Gesetzt: Choreogel -> https://archives.bulbagarden.net/media/upload/6/66/0741Oricorio-Pom-Pom.png
Gesetzt: Choreogel -> https://archives.bulbagarden.net/media/upload/2/23/0741Oricorio-Pa%27u.png
Gesetzt: Choreogel -> https://archives.bulbagarden.net/media/upload/8/8d/0741Oricorio-Sensu.png
Gesetzt: Wolwerock -> https://archives.bulbagarden.net/media/upload/4/46/0745Lycanroc-Midnight.png
Gesetzt: Wolwerock -> https://archives.bulbagarden.net/media/upload/7/7b/0745Lycanroc-Dusk.png
Gesetzt: Lusardin -> https://archives.bulbagarden.net/media/upload/a/a1/0746Wishiwashi-School.png
Gesetzt: Tectass -> https://archives.bulbagarden.net/media/upload/c/c7/0768Golisopod-Mega.png
Gesetzt: Meteno -> https://archives.bulbagarden.net/media/upload/8/84/0774Minior-Core.png

In [18]:
json_path = "../data/pokemon/pokedex_extended_right_link.json"
df_edited = pd.read_json(json_path, orient="records")

removed_entries = 0
merged_types = 0
rows_changed = 0

for row_idx, row in df_edited.iterrows():
    more_forms = row.get("weitere_erscheinungsformen")
    more_devs = row.get("weitere_entwicklungen")

    forms_list = more_forms if isinstance(more_forms, list) else []
    devs_list = more_devs if isinstance(more_devs, list) else []

    # Gemeinsame Sicht auf beide Listen
    all_forms = []
    for i, entry in enumerate(forms_list):
        if isinstance(entry, dict):
            all_forms.append(("forms", i, entry))
    for i, entry in enumerate(devs_list):
        if isinstance(entry, dict):
            all_forms.append(("devs", i, entry))

    # Nach sprite_bulbapedia gruppieren
    by_sprite = {}
    for source, idx, entry in all_forms:
        sprite = entry.get("sprite_bulbapedia")
        if not isinstance(sprite, str) or not sprite.strip():
            continue
        key = sprite.strip()
        by_sprite.setdefault(key, []).append((source, idx, entry))

    to_remove_forms = set()
    to_remove_devs = set()
    changed_this_row = False

    for _, group in by_sprite.items():
        if len(group) < 2:
            continue

        with_link = [g for g in group if isinstance(g[2].get("link_bulbpedia"), str) and g[2].get("link_bulbpedia").strip()]
        without_link = [g for g in group if not (isinstance(g[2].get("link_bulbpedia"), str) and g[2].get("link_bulbpedia").strip())]

        if not with_link or not without_link:
            continue

        # Behalte den ersten Eintrag mit link_bulbpedia
        keep_source, keep_idx, keep_entry = with_link[0]

        for drop_source, drop_idx, drop_entry in without_link:
            # typ1/typ2 vom zu löschenden Eintrag übernehmen, falls im Keep-Eintrag leer
            for typ_key in ["typ1", "typ2"]:
                drop_val = drop_entry.get(typ_key)
                keep_val = keep_entry.get(typ_key)

                drop_has = isinstance(drop_val, str) and drop_val.strip()
                keep_has = isinstance(keep_val, str) and keep_val.strip()

                if drop_has and not keep_has:
                    keep_entry[typ_key] = drop_val
                    merged_types += 1

            if drop_source == "forms":
                to_remove_forms.add(drop_idx)
            else:
                to_remove_devs.add(drop_idx)

            removed_entries += 1
            changed_this_row = True

    if to_remove_forms:
        forms_list = [entry for i, entry in enumerate(forms_list) if i not in to_remove_forms]
        df_edited.at[row_idx, "weitere_erscheinungsformen"] = forms_list

    if to_remove_devs:
        devs_list = [entry for i, entry in enumerate(devs_list) if i not in to_remove_devs]
        df_edited.at[row_idx, "weitere_entwicklungen"] = devs_list

    if changed_this_row:
        rows_changed += 1

print(f"Geänderte Zeilen: {rows_changed}")
print(f"Entfernte Duplikat-Einträge ohne link_bulbpedia: {removed_entries}")
print(f"Übernommene typ1/typ2-Werte: {merged_types}")

out_path = "../data/pokemon/pokedex_extended_cleaned.json"
df_edited.to_json(out_path, orient="records", force_ascii=False, indent=2)
print(f"Gespeichert: {out_path}")

Geänderte Zeilen: 67
Entfernte Duplikat-Einträge ohne link_bulbpedia: 79
Übernommene typ1/typ2-Werte: 77
Gespeichert: ../data/pokemon/pokedex_extended_cleaned.json